### ISSUE TITLE
Fix the ggmap

### ISSUE THREAD

**Issue by MikePapaWhisky** [vbonhomme/GrMoEx#1]
Get error "ggplot2 doesn't know how to deal with data of class function" when selecting tab. NB: ggmap installed and loaded. Having had a look at the code the problem might be something to do with object 'Site' which seems to keep appearing.

    Listening on http://127.0.0.1:3348
    Note: the specification for S3 class “AsIs” in package ‘jsonlite’ seems equivalent to one from package ‘RJSONIO’: not turning on duplicate class definitions for this class.
    Error : ggplot2 doesn't know how to deal with data of class function

**Comment by vbonhomme** [comment]
complicated one: environments...
gonna dedicate some time after all other features.

2015-07-08 13:12 GMT+02:00 Michael Paul Wallace <notifications@github.com>:

> Get error "ggplot2 doesn't know how to deal with data of class function"
> when selecting tab. NB: ggmap installed and loaded. Having had a look at
> the code the problem might be something to do with object 'Site' which
> seems to keep appearing.
>
> Listening on http://127.0.0.1:3348
> Note: the specification for S3 class “AsIs” in package ‘jsonlite’ seems equivalent to one from package ‘RJSONIO’: not turning on duplicate class definitions for this class.
> Error : ggplot2 doesn't know how to deal with data of class function
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/vbonhomme/GrMoEx/issues/1>.
>



-- 
vincentbonhomme.fr <http://www.vincentbonhomme.fr>

**Comment by vbonhomme** [comment]
done.
