### ISSUE TITLE
Feature request: n in CV

### ISSUE THREAD

**Issue by MikePapaWhisky** [vbonhomme/GrMoEx#10]
It would be nice to have the count of classifications in the LDA CV - some of the sample sizes are pretty small and its quite hard to interpret shades of red in such cases,

**Comment by vbonhomme** [comment]
you mean frequencies rather than counts ?

2015-07-09 13:05 GMT+02:00 Michael Paul Wallace <notifications@github.com>:

> It would be nice to have the count of classifications in the LDA CV - some
> of the sample sizes are pretty small and its quite hard to interpret shades
> of red in such cases,
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/vbonhomme/GrMoEx/issues/10>.
>



-- 
vincentbonhomme.fr <http://www.vincentbonhomme.fr>

**Comment by vbonhomme** [comment]
and/or counts in LDAdetails tab ?

2015-07-09 13:17 GMT+02:00 Vincent Bonhomme <bonhomme.vincent@gmail.com>:

> you mean frequencies rather than counts ?
>
> 2015-07-09 13:05 GMT+02:00 Michael Paul Wallace <notifications@github.com>
> :
>
>> It would be nice to have the count of classifications in the LDA CV -
>> some of the sample sizes are pretty small and its quite hard to interpret
>> shades of red in such cases,
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/vbonhomme/GrMoEx/issues/10>.
>>
>
>
>
> --
> vincentbonhomme.fr <http://www.vincentbonhomme.fr>
>



-- 
vincentbonhomme.fr <http://www.vincentbonhomme.fr>

**Comment by MikePapaWhisky** [comment]
Whatever number you deem appropriate :-) Maybe Super Mario highscores?

**Comment by vbonhomme** [comment]
done on the confusion matrix itself plus you still have frequencies on the "LDA details" tab.
