### ISSUE TITLE
Feature request: ungrouped samples for LDA

### ISSUE THREAD

**Issue by MikePapaWhisky** [vbonhomme/GrMoEx#11]
I'm putting this on GitHub as I think its a rather big one. We really want to be able to have certain samples marked as ungrouped, such that when we look at the LDA - the LDA doesn't try to attribute any samples to the 'ungrounded' category.

#### Very simple example
Three taxa (or taxa groups selected): *TBOE*, *TMON* and *TBOE-MONO*
**Currently** - the LDA will specify for each sample which of these **three** groups they are best fitted within.
**Desire** - *TBOE-MONO* is marked as ungrouped such that the LDA will try to fit each sample into either *TBOE* or *TMON* (but no sample can be classified as *TBOE-MONO*).

--

###### A generic solution would be most welcome

**Comment by vbonhomme** [comment]
do you mean :

1. calculate and LDA based on Tboe and Tmon
2. classify Tmon using it to see where it "falls" ?

2015-07-09 13:34 GMT+02:00 Michael Paul Wallace <notifications@github.com>:

> I'm putting this on GitHub as I think its a rather big one. We really want
> to be able to have certain samples marked as ungrouped, such that when we
> look at the LDA - the LDA doesn't try to attribute any samples to the
> 'ungrounded' category.
> Very simple example
>
> Three taxa (or taxa groups selected): *TBOE*, *TMON* and *TBOE-MONO*
> *Currently* - the LDA will specify for each sample which of these *three*
> groups they are best fitted within.
> *Desire* - *TBOE-MONO* is marked as ungrouped such that the LDA will try
> to fit each sample into either *TBOE* or *TMON* (but no sample can be
> classified as *TBOE-MONO*).
>  A generic solution would be most welcome
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/vbonhomme/GrMoEx/issues/11>.
>



-- 
vincentbonhomme.fr <http://www.vincentbonhomme.fr>

**Comment by vbonhomme** [comment]
ping Michael

2015-07-09 13:39 GMT+02:00 Vincent Bonhomme <bonhomme.vincent@gmail.com>:

> do you mean :
>
> 1. calculate and LDA based on Tboe and Tmon
> 2. classify Tmon using it to see where it "falls" ?
>
> 2015-07-09 13:34 GMT+02:00 Michael Paul Wallace <notifications@github.com>
> :
>
>> I'm putting this on GitHub as I think its a rather big one. We really
>> want to be able to have certain samples marked as ungrouped, such that when
>> we look at the LDA - the LDA doesn't try to attribute any samples to the
>> 'ungrounded' category.
>> Very simple example
>>
>> Three taxa (or taxa groups selected): *TBOE*, *TMON* and *TBOE-MONO*
>> *Currently* - the LDA will specify for each sample which of these *three*
>> groups they are best fitted within.
>> *Desire* - *TBOE-MONO* is marked as ungrouped such that the LDA will try
>> to fit each sample into either *TBOE* or *TMON* (but no sample can be
>> classified as *TBOE-MONO*).
>>  A generic solution would be most welcome
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/vbonhomme/GrMoEx/issues/11>.
>>
>
>
>
> --
> vincentbonhomme.fr <http://www.vincentbonhomme.fr>
>



-- 
vincentbonhomme.fr <http://www.vincentbonhomme.fr>

**Comment by MikePapaWhisky** [comment]
Yes. That sounds right, so long as you meant TBOE-MONO in point 2.

**Comment by vbonhomme** [comment]
va bene,
I start in 5min
would you say that
 * the PCA should be calculated on the 3 taxa,
 * and the LDA on a subset of those scores,
 * then the remaining be injected in the previously calculated model ?

2015-07-09 15:01 GMT+02:00 Michael Paul Wallace <notifications@github.com>:

> Yes. That sounds right, so long as you meant TBOE-MONO in point 2.
> On 9 Jul 2015 12:39, "Vincent Bonhomme" <notifications@github.com> wrote:
>
> > do you mean :
> >
> > 1. calculate and LDA based on Tboe and Tmon
> > 2. classify Tmon using it to see where it "falls" ?
> >
> > 2015-07-09 13:34 GMT+02:00 Michael Paul Wallace <
> notifications@github.com
> > >:
> >
> > > I'm putting this on GitHub as I think its a rather big one. We really
> > want
> > > to be able to have certain samples marked as ungrouped, such that when
> we
> > > look at the LDA - the LDA doesn't try to attribute any samples to the
> > > 'ungrounded' category.
> > > Very simple example
> > >
> > > Three taxa (or taxa groups selected): *TBOE*, *TMON* and *TBOE-MONO*
> > > *Currently* - the LDA will specify for each sample which of these
> *three*
> > > groups they are best fitted within.
> > > *Desire* - *TBOE-MONO* is marked as ungrouped such that the LDA will
> try
> > > to fit each sample into either *TBOE* or *TMON* (but no sample can be
> > > classified as *TBOE-MONO*).
> > > A generic solution would be most welcome
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <https://github.com/vbonhomme/GrMoEx/issues/11>.
> > >
> >
> >
> >
> > --
> > vincentbonhomme.fr <http://www.vincentbonhomme.fr>
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/vbonhomme/GrMoEx/issues/11#issuecomment-119923352>.
>
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/vbonhomme/GrMoEx/issues/11#issuecomment-119954096>.
>



-- 
vincentbonhomme.fr <http://www.vincentbonhomme.fr>

**Comment by MikePapaWhisky** [comment]
I think so. Shouldn't really affect the PCA.  Not sure how you're going to
get this into the Shiny GUI. Look forward to your solution.

NB: I'm presenting your GrMoEx tomorrow, and at the moment is gorgeous as
it is. So maybe fork this issue until tomorrow afternoon?

**Comment by vbonhomme** [comment]
I like to live dangereously.


2015-07-09 15:49 GMT+02:00 Michael Paul Wallace <notifications@github.com>:

> I think so. Shouldn't really affect the PCA. Not sure how you're going to
> get this into the Shiny GUI. Look forward to your solution.
>
> NB: I'm presenting your GrMoEx tomorrow, and at the moment is gorgeous as
> it is. So maybe fork this issue until tomorrow afternoon?
> On 9 Jul 2015 14:21, "Vincent Bonhomme" <notifications@github.com> wrote:
>
> > va bene,
> > I start in 5min
> > would you say that
> > * the PCA should be calculated on the 3 taxa,
> > * and the LDA on a subset of those scores,
> > * then the remaining be injected in the previously calculated model ?
> >
> > 2015-07-09 15:01 GMT+02:00 Michael Paul Wallace <
> notifications@github.com
> > >:
> >
> > > Yes. That sounds right, so long as you meant TBOE-MONO in point 2.
> > > On 9 Jul 2015 12:39, "Vincent Bonhomme" <notifications@github.com>
> > wrote:
> > >
> > > > do you mean :
> > > >
> > > > 1. calculate and LDA based on Tboe and Tmon
> > > > 2. classify Tmon using it to see where it "falls" ?
> > > >
> > > > 2015-07-09 13:34 GMT+02:00 Michael Paul Wallace <
> > > notifications@github.com
> > > > >:
> > > >
> > > > > I'm putting this on GitHub as I think its a rather big one. We
> really
> > > > want
> > > > > to be able to have certain samples marked as ungrouped, such that
> > when
> > > we
> > > > > look at the LDA - the LDA doesn't try to attribute any samples to
> the
> > > > > 'ungrounded' category.
> > > > > Very simple example
> > > > >
> > > > > Three taxa (or taxa groups selected): *TBOE*, *TMON* and
> *TBOE-MONO*
> > > > > *Currently* - the LDA will specify for each sample which of these
> > > *three*
> > > > > groups they are best fitted within.
> > > > > *Desire* - *TBOE-MONO* is marked as ungrouped such that the LDA
> will
> > > try
> > > > > to fit each sample into either *TBOE* or *TMON* (but no sample can
> be
> > > > > classified as *TBOE-MONO*).
> > > > > A generic solution would be most welcome
> > > > >
> > > > > —
> > > > > Reply to this email directly or view it on GitHub
> > > > > <https://github.com/vbonhomme/GrMoEx/issues/11>.
> > > > >
> > > >
> > > >
> > > >
> > > > --
> > > > vincentbonhomme.fr <http://www.vincentbonhomme.fr>
> > > >
> > > > —
> > > > Reply to this email directly or view it on GitHub
> > > > <
> https://github.com/vbonhomme/GrMoEx/issues/11#issuecomment-119923352
> > >.
> > >
> > > >
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <https://github.com/vbonhomme/GrMoEx/issues/11#issuecomment-119954096
> >.
> > >
> >
> >
> >
> > --
> > vincentbonhomme.fr <http://www.vincentbonhomme.fr>
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/vbonhomme/GrMoEx/issues/11#issuecomment-119962230>.
>
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/vbonhomme/GrMoEx/issues/11#issuecomment-119974948>.
>



-- 
vincentbonhomme.fr <http://www.vincentbonhomme.fr>

**Comment by MikePapaWhisky** [comment]
I'm sure you do... when you're in another country sat in your underpants.

**Comment by vbonhomme** [comment]
:o))

2015-07-09 15:58 GMT+02:00 Michael Paul Wallace <notifications@github.com>:

> I'm sure you do... when you're in another country sat in your underpants.
>
> On 9 Jul 2015 14:52, "Vincent Bonhomme" <notifications@github.com> wrote:
>
> > I like to live dangereously.
> >
> >
> > 2015-07-09 15:49 GMT+02:00 Michael Paul Wallace <
> notifications@github.com
> > >:
> >
> > > I think so. Shouldn't really affect the PCA. Not sure how you're going
> to
> > > get this into the Shiny GUI. Look forward to your solution.
> > >
> > > NB: I'm presenting your GrMoEx tomorrow, and at the moment is gorgeous
> as
> > > it is. So maybe fork this issue until tomorrow afternoon?
> > > On 9 Jul 2015 14:21, "Vincent Bonhomme" <notifications@github.com>
> > wrote:
> > >
> > > > va bene,
> > > > I start in 5min
> > > > would you say that
> > > > * the PCA should be calculated on the 3 taxa,
> > > > * and the LDA on a subset of those scores,
> > > > * then the remaining be injected in the previously calculated model ?
> > > >
> > > > 2015-07-09 15:01 GMT+02:00 Michael Paul Wallace <
> > > notifications@github.com
> > > > >:
> > > >
> > > > > Yes. That sounds right, so long as you meant TBOE-MONO in point 2.
> > > > > On 9 Jul 2015 12:39, "Vincent Bonhomme" <notifications@github.com>
> > > > wrote:
> > > > >
> > > > > > do you mean :
> > > > > >
> > > > > > 1. calculate and LDA based on Tboe and Tmon
> > > > > > 2. classify Tmon using it to see where it "falls" ?
> > > > > >
> > > > > > 2015-07-09 13:34 GMT+02:00 Michael Paul Wallace <
> > > > > notifications@github.com
> > > > > > >:
> > > > > >
> > > > > > > I'm putting this on GitHub as I think its a rather big one. We
> > > really
> > > > > > want
> > > > > > > to be able to have certain samples marked as ungrouped, such
> that
> > > > when
> > > > > we
> > > > > > > look at the LDA - the LDA doesn't try to attribute any samples
> to
> > > the
> > > > > > > 'ungrounded' category.
> > > > > > > Very simple example
> > > > > > >
> > > > > > > Three taxa (or taxa groups selected): *TBOE*, *TMON* and
> > > *TBOE-MONO*
> > > > > > > *Currently* - the LDA will specify for each sample which of
> these
> > > > > *three*
> > > > > > > groups they are best fitted within.
> > > > > > > *Desire* - *TBOE-MONO* is marked as ungrouped such that the LDA
> > > will
> > > > > try
> > > > > > > to fit each sample into either *TBOE* or *TMON* (but no sample
> > can
> > > be
> > > > > > > classified as *TBOE-MONO*).
> > > > > > > A generic solution would be most welcome
> > > > > > >
> > > > > > > —
> > > > > > > Reply to this email directly or view it on GitHub
> > > > > > > <https://github.com/vbonhomme/GrMoEx/issues/11>.
> > > > > > >
> > > > > >
> > > > > >
> > > > > >
> > > > > > --
> > > > > > vincentbonhomme.fr <http://www.vincentbonhomme.fr>
> > > > > >
> > > > > > —
> > > > > > Reply to this email directly or view it on GitHub
> > > > > > <
> > > https://github.com/vbonhomme/GrMoEx/issues/11#issuecomment-119923352
> > > > >.
> > > > >
> > > > > >
> > > > >
> > > > > —
> > > > > Reply to this email directly or view it on GitHub
> > > > > <
> > https://github.com/vbonhomme/GrMoEx/issues/11#issuecomment-119954096
> > > >.
> > > > >
> > > >
> > > >
> > > >
> > > > --
> > > > vincentbonhomme.fr <http://www.vincentbonhomme.fr>
> > > >
> > > > —
> > > > Reply to this email directly or view it on GitHub
> > > > <
> https://github.com/vbonhomme/GrMoEx/issues/11#issuecomment-119962230
> > >.
> > >
> > > >
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <https://github.com/vbonhomme/GrMoEx/issues/11#issuecomment-119974948
> >.
> > >
> >
> >
> >
> > --
> > vincentbonhomme.fr <http://www.vincentbonhomme.fr>
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/vbonhomme/GrMoEx/issues/11#issuecomment-119976927>.
>
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/vbonhomme/GrMoEx/issues/11#issuecomment-119985355>.
>



-- 
vincentbonhomme.fr <http://www.vincentbonhomme.fr>

**Comment by vbonhomme** [comment]
done. see 'Classify tab'
