### ISSUE TITLE
LDA classify

### ISSUE THREAD

**Issue by MikePapaWhisky** [vbonhomme/GrMoEx#13]
Great progress. Really like it. An issue is going to be though that we can't yet pre-group certain taxa together. The taxa which are 'Reference taxa' are tied to the original taxa name (in the silhouette filename). What we want to do is say classify *Mystery Grain X* to *Known Grain A* or *Known Grain B & C*. We could use taxonomic grouping variables for this. E.g. the reference taxa list could be populated with the levels of .taxa or .taxaparent or some other list from define_groups.

**Comment by vbonhomme** [comment]
"We could use taxonomic grouping variables for this"
> yes. gonna add a selector when you'll have defined all metagroups

2015-07-09 21:58 GMT+02:00 Michael Paul Wallace <notifications@github.com>:

> Great progress. Really like it. An issue is going to be though that we
> can't yet pre-group certain taxa together. The taxa which are 'Reference
> taxa' are tied to the original taxa name (in the silhouette filename). What
> we want to do is say classify *Mystery Grain X* to *Known Grain A* or *Known
> Grain B & C*. We could use taxonomic grouping variables for this. E.g.
> the reference taxa list could be populated with the levels of .taxa or
> .taxaparent or some other list from define_groups.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/vbonhomme/GrMoEx/issues/13>.
>



-- 
vincentbonhomme.fr <http://www.vincentbonhomme.fr>

**Comment by MikePapaWhisky** [comment]
>gonna add a selector when you'll have defined all metagroups

We might need something more generic than waiting for the metagroups; the metagroups will likely grow organically depending on the results of initial LDAs. 

>*Hrmmmm, that's interesting - what happens if we add that to that group...*
- Prof. G. Jones, in the future

**Comment by vbonhomme** [comment]
so eventually you need to define groups on the fly in GrMoEx plus the
define_group for the big and relatively constant ones ?

2015-07-10 10:55 GMT+02:00 Michael Paul Wallace <notifications@github.com>:

> gonna add a selector when you'll have defined all metagroups
>
> We might need something more generic than waiting for the metagroups; the
> metagroups will likely grow organically depending on the results of initial
> LDAs.
>
> *Hrmmmm, that's interesting - what happens if we add that to that group...*
>
>    - Prof. G. Jones, in the future
>
>  —
> Reply to this email directly or view it on GitHub
> <https://github.com/vbonhomme/GrMoEx/issues/13#issuecomment-120304939>.
>



-- 
vincentbonhomme.fr <http://www.vincentbonhomme.fr>

**Comment by MikePapaWhisky** [comment]
In either case (i.e. for the LDA classification or the PCA grouping variables) on-the-fly would be amazing, but would be especially useful. We'd be happy to work with the define_groups.csv but obviously its a bit less slick having to come out of GrMoEx to add members to a group (especially since it currently requires a RStudio restart).

**Comment by vbonhomme** [comment]
* the restart is a minor problem (ie can be solved) (btw : Session >
Restart R does the job).
* i think about a on the fly grouping thing

the good point is that I will have amny elements to recycle for a
shinyMomocs :o)


2015-07-10 11:05 GMT+02:00 Michael Paul Wallace <notifications@github.com>:

> In either case (i.e. for the LDA classification or the PCA grouping
> variables) on-the-fly would be amazing, but would be especially useful.
> We'd be happy to work with the define_groups.csv but obviously its a bit
> less slick having to come out of GrMoEx to add members to a group
> (especially since it currently requires a RStudio restart).
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/vbonhomme/GrMoEx/issues/13#issuecomment-120308346>.
>



-- 
vincentbonhomme.fr <http://www.vincentbonhomme.fr>

**Comment by vbonhomme** [comment]
* for grouping on the fly see : shiny::runGist("1b1aec1ee4fc0c65e48b")
*  "especially since it currently requires a RStudio restart)" -> now fixed

**Comment by MikePapaWhisky** [comment]
Sent an email regarding your runGist(my balls). Looks like lots of potential.
No restart fix is nice, so now we just edit the CSV, source III then run IV. Yeah?

**Comment by vbonhomme** [comment]
no the idea would really be to define groups on the fly from GrMoEx. I'm on it

**Comment by vbonhomme** [comment]
so to be sure of what we want:
1. select some Taxa and attribute them a label
2. repeat 1. n times (with n >= 1)
3. classify (as implemented now) a single taxa into one of (n+1) groups defined above

**Comment by vbonhomme** [comment]
though one.
we now have a 'classify' method in Momocs. Update required.

**Comment by vbonhomme** [comment]
also a simplified ['on the fly'](https://gist.github.com/vbonhomme/572c280ca6bec607bb8e) for the needs here

**Comment by vbonhomme** [comment]
the binding between GrMoEx, and the two points above remains

**Comment by MikePapaWhisky** [comment]
I'm not sure the script ['on the fly'] (https://gist.github.com/vbonhomme/572c280ca6bec607bb8e) will necessarily do what we want. In an attempt to be perfectly clear:
1. some taxa (n => 1) are assigned to a group (type = ```assigned```)
2. repeat step 1 n times (n >= 2)
3. some taxa (n >= 1) are assigned to the group (type = ```unassigned```)
4. any remaining (not placed in a group) taxa are excluded from the LDA
5. LDA calculated on the ```assigned``` groups 
6. Individual samples in the ```unassigned``` are classified to the ```assigned``` groups

*Pretty close to what you said, does it match what you had in mind? Note that this is a priority for Glynis.*

**Comment by vbonhomme** [comment]
that's also my priority but a tough one.
should take at lead a couple of hours since I include some generic method
in Momocs in the same move.

that was exactly what I have in mind except that the fact that 3) may be
one or more reqire one more twist in def groups on the fly.

2015-07-14 13:49 GMT+02:00 Michael Paul Wallace <notifications@github.com>:

> I'm not sure the script 'on the fly'
> <https://gist.github.com/vbonhomme/572c280ca6bec607bb8e> will necessarily
> do what we want. In an attempt to be perfectly clear:
> 1. some taxa (n => 1) are assigned to a group (type = assigned)
> 2. repeat step 1 n times (n >= 2)
> 3. some taxa (n >= 1) are assigned to the group (type = unassigned)
> 4. any remaining (not placed in a group) taxa are excluded from the LDA
> 5. LDA calculated on the assigned groups
> 6. Individual samples in the unassigned are classified to the assigned
> groups
>
> *Pretty close to what you said, does it match what you had in mind? Note
> that this is a priority for Glynis.*
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/vbonhomme/GrMoEx/issues/13#issuecomment-121213371>.
>



-- 
vincentbonhomme.fr <http://www.vincentbonhomme.fr>

**Comment by MikePapaWhisky** [comment]
Good luck.

**Comment by vbonhomme** [comment]
Done. \o/  took a lot of pain. needs the last Momocs version

**Comment by MikePapaWhisky** [comment]
Great. Might not get a chance to look until next Monday - have a window on
Friday morning though. Sorry for the pain, but I know you love it - and
this was a big one.
