### ISSUE TITLE
Classify plot

### ISSUE THREAD

**Issue by MikePapaWhisky** [vbonhomme/GrMoEx#14]
The plot on Classify is really neat, but we kind of need some way of knowing which classification grains are being put where. Maybe a table of classification scores indexed by site and period?

**Comment by vbonhomme** [comment]
gonna try tonight

2015-07-09 21:59 GMT+02:00 Michael Paul Wallace <notifications@github.com>:

> The plot on Classify is really neat, but we kind of need some way of
> knowing which classification grains are being put where. Maybe a table of
> classification scores indexed by site and period?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/vbonhomme/GrMoEx/issues/14>.
>



-- 
vincentbonhomme.fr <http://www.vincentbonhomme.fr>

**Comment by vbonhomme** [comment]
done.
