### ISSUE TITLE
Scrolling sidebar

### ISSUE THREAD

**Issue by MikePapaWhisky** [vbonhomme/GrMoEx#16]
Is there anyway to scroll the sidebar independently of the main panel? Given we [unavoidably] have so many options its kind of annoying that the plot goes out of view when I scroll down to reach the lower options. 

On a side note, how do I control the order of options in the sidepanel? I'd rather have the cosmetics near the top. I just assumed it would be based on the order of functions in the ui section of the script - but that doesn't seem to work.

**Comment by vbonhomme** [comment]
2015-07-10 10:58 GMT+02:00 Michael Paul Wallace <notifications@github.com>:

> Is there anyway to scroll the sidebar independently of the main panel?
> Given we [unavoidably] have so many options its kind of annoying that the
> plot goes out of view when I scroll down to reach the lower options.
>

I'm thinking about a redesign a removing (most of) the sidebar. But not
really really convinced so far.


> On a side note, how do I control the order of options in the sidepanel?
> I'd rather have the cosmetics near the top. I just assumed it would be
> based on the order of functions in the ui section of the script - but that
> doesn't seem to work.
>

It should though. send me a mockup (visual or text) ad I'll do it

> —
> Reply to this email directly or view it on GitHub
> <https://github.com/vbonhomme/GrMoEx/issues/16>.
>



-- 
vincentbonhomme.fr <http://www.vincentbonhomme.fr>

**Comment by MikePapaWhisky** [comment]
IV_GrMoEx - copy.R
```
################################################################################
#                           Morpho Grain Explorer                              #
################################################################################

### Libraries
# order matters.
library(MASS)
library(shiny)
library(dplyr)
library(Momocs)
library(ggplot2)
library(ggmap)


### Data import
load("arch_ready.rda")
# catch "meta-groups" groups
dotted_cols <- colnames(A$fac)[grep(pattern = "\\.", colnames(A$fac))]
# load the map
# we prepare for the map`
# center_coords <- c(mean(range(unique(A$fac$Long))), mean(range(unique(A$fac$Lat))))
# crescent_map <- get_map(center_coords, zoom=6, maptype = "watercolor")
# save(crescent_map, file="crescent_map.rda")
load("crescent_map.rda")

# Server #######################################################################
server <- function(input, output) {

  # cosmetics. because selectInput accepts characters only, not functions.
  palette_deliver <- function(input){
    switch(input,
           "col_spring"=col_spring,
           "col_summer"=col_summer,
           "col_autumn"=col_autumn,
           "col_qual"=col_qual,
           "col_solarized"=col_solarized)
  }

  # reactive section ###########################################################
  # observe any change concerning filtering and recalculate a PCA
  Ap <- reactive({
    A %>% at_least(input$fac1, input$N) %>%
      filter(Taxa %in% input$Taxa, Site_phase %in% input$Site_phase) %>%
      PCA()
  })

  # same thing for LDA
  Al <- reactive({
    if (is.null(input$fac2)) {
      fac <- input$fac1
    } else {
      fac <- as.formula(paste("~", input$fac1, "+", input$fac2))
    }
    LDA(Ap(), fac, retain=0.99, verbose=FALSE)
  })

  # Used by the map counts how many grain per Site
  df_count <- reactive({
    select(Ap()$fac, Site, Lat, Long) %>%
      count(Site, Lat, Long) %>%
      ungroup()
  })

  # PCA ########################################################################
  # produces the PCA plot (and make it savable)
  make_PCA_plot <- function(){
    if (is.null(input$fac2)) {
      fac <- input$fac1
    } else {
      fac <- as.formula(paste("~", input$fac1, "+", input$fac2))
    }
    plot(Ap(),
         fac = fac,
         zoom=input$zoom, xax=input$xax, yax=input$yax,
         palette=palette_deliver(input$palette),
         morphospace = input$morphospace, pos.shp=input$pos.shp,
         points=input$points, ellipses=input$ellipses,
         ellipsesax=input$ellipsesax,
         chull=input$chull)
  }
  # PCA and its plot
  output$PCA_plot <- renderPlot({
    make_PCA_plot()
  },
  width=exprToFunction(input$plot_width),
  height=exprToFunction(input$plot_width))

  # PCA saver
  observeEvent(input$pdf, {
    name <- paste0("saved_graphs/", input$pdfname, "_",
                   strftime(Sys.time(), format="%Y-%m-%d-%H-%M-%S"), ".pdf")
    pdf(name)
    make_PCA_plot()
    dev.off()
    cat( " * graph saved as", name, "\n")
  })

  # Map ########################################################################
  # plots a map of the fertile crescent (or its left horn)
  output$plotMap <- renderPlot({
    f2n <- function(x) as.numeric(as.character(x))
    dfc <- mutate(df_count(),
                  Site=as.character(Site),
                  Lat=f2n(Lat),
                  Long=f2n(Long),
                  n=as.numeric(n))
    gg <- ggmap(crescent_map, darken=c(3/4, color="#FFFFFF")) +
      geom_point(data=dfc, aes(x=Long, y=Lat, size=n), fill="#000000", alpha=0.1, shape=16) +
      scale_size_area(max_size = 25) +
      geom_text(data=dfc, aes(x=Long, y=Lat, label=n), size=4) +
      geom_text(data=dfc, aes(x=Long, y=Lat+0.25, label=Site), size=3) +
      theme(legend.position="none")
    suppressWarnings(print(gg))
  },
  width=exprToFunction(input$plot_width),
  height=exprToFunction(input$plot_width))

  output$dfc <- renderPrint(df_count())

  # Sample sizes ###############################################################
  output$N_Period <- renderTable(
    select(Ap()$fac, Period) %>% count(Period) %>% arrange(desc(n))
  )
  output$N_Site <- renderTable({
    select(Ap()$fac, Site) %>% count(Site) %>% arrange(desc(n))
  })
  output$N_Taxa <- renderTable(
    select(Ap()$fac, Taxa) %>% count(Taxa) %>% arrange(desc(n))
  )
  output$N_Site_phase <- renderTable(
    select(Ap()$fac, Site_phase) %>% count(Site_phase) %>% arrange(desc(n))
  )

  # LDA and its plot ###########################################################
  output$LDA_plot <- renderPlot({
    plot(Al(),
         fac = fac,
         zoom=input$zoom, xax=input$xax, yax=input$yax,
         palette=palette_deliver(input$palette),
         points=input$points, ellipses=input$ellipses,
         ellipsesax=input$ellipsesax,
         chull=input$chull)
  },
  width=exprToFunction(input$plot_width),
  height=exprToFunction(input$plot_width))

  # LDA confusion matrix
  output$LDA_tab <- renderPlot({
    gg <- plot_CV(Al(), freq=FALSE, rm0=TRUE, cex=3) + coord_equal()
    print(gg)
  },
  width=exprToFunction(input$plot_width),
  height=exprToFunction(input$plot_width))

  # LDA % of correct classification
  output$LDA_correct <- renderPrint({
    print(round(Al()$CV.correct * 100), 1)
  })

  # % of correct classification per class
  output$LDA_ce <- renderPrint({
    print(round(Al()$CV.ce * 100, 1))
  })

  # Classify ###################################################################
  make_silhouette <- function(){
    probs <- classify()$probs
    probs <- probs[order(probs[, 1], decreasing = TRUE), ]
    cols <- col_qual(ncol(probs))
    barplot(t(probs), names.arg=NULL, space=0,
            col=cols, border=NA, axisnames=FALSE, xaxs="i")
    legend("bottomleft", fill = cols, legend = colnames(probs), bty="n")
  }

  classify <- reactive({
    # shortcut
    ref <- input$classify_ref
    unk <- input$classify_unk
    # calculate a PCA using all taxa
    P0 <- A %>%
      filter(Taxa %in% c(ref, unk)) %>%
      PCA()
    # calculate an LDA using all but the unknown taxa
    L0 <- P0 %>%
      filter(Taxa != unk) %>%
      LDA("Taxa", retain=0.99, verbose=FALSE)
    # extract and prepare scores of the unknown taxa
    P1_all <- P0 %>%
      filter(Taxa == unk)
    P1 <- P1_all$x[, 1:ncol(L0$x)]

    # classify using the MASS::lda
    pred <- predict(L0$mod, P1)

    counts <- table(pred$class)
    N_unk     <- sum(counts)
    pc    <- round((counts / sum(counts))*100, 2)
    probs <- pred$posterior
    probs_fac <- cbind(pred$posterior, select(P1_all$fac, Site, Period)) %>%
      group_by(Site, Period) %>%
      summarise_each(funs(mean))
    # not particularly clean
    # probs_fac <- bind_cols(select(probs_fac, 1:2), round(select(probs_fac, 3)))

    list(N_ref=nrow(L0$x),
         N_ref_tab=table(L0$fac),
         N_unk=N_unk,
         counts=counts,
         pc=pc,
         probs=probs,
         probs_fac=probs_fac)
  })

  output$classify_N_ref  <- renderPrint(classify()$N_ref)
  output$classify_N_ref_tab  <- renderPrint(classify()$N_ref_tab)
  output$classify_N_unk  <- renderPrint(classify()$N_unk)
  output$classify_counts <- renderPrint(classify()$counts)
  output$classify_pc     <- renderPrint(classify()$pc)
  output$classify_probs_fac <- renderDataTable(classify()$probs_fac)
  output$classify_plot   <- renderPlot(make_silhouette(),
                                       width=exprToFunction(input$plot_width),
                                       height=exprToFunction(input$plot_width))

  # Traditional ################################################################
  # bloody reactive
  make_trad_plot <- function(){
    f2n <- function(x) as.numeric(as.character(x))
    dft <- mutate(Ap()$fac,
                  Length=f2n(Length),
                  Width=f2n(Width),
                  Height=f2n(Height),
                  BCstart=f2n(BCstart),
                  BCmean=f2n(BCmean),
                  BCend=f2n(BCend),
                  Lat=f2n(Lat),
                  Long=f2n(Long))

    gg <- ggplot(data=dft) +
      aes_string(x=input$trad_x, y=input$trad_y, col=input$trad_col, shp=input$trad_shp) +
      geom_point()
    if (input$trad_lm) gg <- gg + stat_smooth(method="lm")
    print(gg)
  }

  output$trad_plot <- renderPlot(make_trad_plot(),
                                 width=exprToFunction(input$plot_width),
                                 height=exprToFunction(input$plot_width))

  # output$trad2 <- renderPrint(summary(Ap()$fac))

}

# ui ###########################################################################
# Define UI for random distribution application
ui <- shinyUI(fluidPage(
  ##### Title
  titlePanel("GrMoEx"),
  h6(paste("version", file.info("IV_GrMoEx.R")$mtime)),
  sidebarLayout(
    ##### Sidebar
    sidebarPanel(
      ### Cosmetics section
      h3("Cosmetics"), hr(),
      # plot width
      sliderInput(inputId = "plot_width", label = "Plot width",
                  min=200, max=1600, value=800, step = 100),
      # plot zoom
      sliderInput(inputId="zoom", label="zoom (<=1 to display all points)",
                  min=0.1, max=5, value=1, step=0.1),
      checkboxInput("points",
                    label = "Add points",
                    value = FALSE),
      checkboxInput("ellipses",
                    label = "Add (0.5) confidence ellipses",
                    value = TRUE),
      checkboxInput("ellipsesax",
                    label = "Add (0.5, 0.75, 0.9) confidence ellipses axes",
                    value = FALSE),
      checkboxInput("chull",
                    label = "Add convex hulls",
                    value = FALSE),
      checkboxInput("morphospace",
                    label = "Display morphospace",
                    value = TRUE),
      selectInput("pos.shp",
                  label = "Shape position",
                  choices = list("full" = "full", "range" = "range", "xy"="xy"),
                  selected = "full"),
      # palette picker
      selectInput("palette",
                  label="Color palette",
                  choices=list("col_spring", "col_summer", "col_autumn", "col_qual", "col_solarized"),
                  selected="col_qual"),
      # plot saver
      textInput("pdfname", label = NULL, value = "Name"),
      actionButton("pdf", "Save PCA plot"),
      # here we specify (in 1/12th) the width of the sidebar
      width=3),
      
       ### Covariate section
      h3("Covariates"), hr(),
      # fac1
      selectInput(inputId = "fac1",
                  label="1st grouping factor to use:",
                  choices=c("Taxa", dotted_cols,
                            "Site", "Site_phase", "Region_coarse", "Region_fine",
                            "Period", "BCstart", "BCend", "BCmean"),
                  selected="Taxa",
                  multiple=FALSE,
                  selectize=FALSE),
      # fac2
      selectInput(inputId = "fac2",
                  label="2nd grouping factor to use:",
                  choices=c("NULL", "Taxa", dotted_cols,
                            "Site", "Site_phase", "Region_coarse", "Region_fine",
                            "Period", "BCstart", "BCend", "BCmean"),
                  selected="NULL",
                  multiple=FALSE,
                  selectize=FALSE),

      # axes selection
      h5("PC axes to use"),
      numericInput("xax", label = "Axis1", value = 1, 1, 10, 1),
      numericInput("yax", label = "Axis", value = 2, 1, 10, 1),

      ### Filtering section
      h3("Filtering"), hr(),
      # N in fac1 filtering
      sliderInput("N",
                  label="Min nb of grains per fac1",
                  min=0, max=100, step=1, value=0),
      p("'Ctrl'/'Cmd' is your friend below"),
      # Taxa filtering
      selectInput(inputId = "Taxa",
                  label="Taxa to include:",
                  choices=levels(A$fac$Taxa),
                  selected=levels(A$fac$Taxa),
                  multiple=TRUE, selectize=FALSE, size=20),
      # Site filtering
      selectInput(inputId = "Site_phase",
                  label="Sites x Phase to include:",
                  choices=levels(A$fac$Site_phase),
                  selected=levels(A$fac$Site_phase),
                  multiple=TRUE, selectize=FALSE, size=20),

      

    ##### Main panel
    mainPanel(
      tabsetPanel(type = "pills",
                  tabPanel("PCA",
                           column(12,
                                  plotOutput("PCA_plot"))),
                  tabPanel("LDA plot",
                           plotOutput("LDA_plot")),
                  tabPanel("LDA CV",
                           h5("% of correct classification"),
                           verbatimTextOutput("LDA_correct"),
                           h5("% of correct classification per class"),
                           verbatimTextOutput("LDA_ce"),
                           h5("Confusion matrix (CV leave-1-out)"),
                           plotOutput("LDA_tab")),
                  # Classify ###################################################
                  tabPanel("Classify",
                           column(6,
                                  selectInput(inputId = "classify_ref",
                                              label="Reference taxa:",
                                              choices=levels(A$fac$Taxa),
                                              selected=NULL,
                                              multiple=TRUE,
                                              selectize=FALSE, size=20)),
                           column(6,
                                  selectInput(inputId = "classify_unk",
                                              label="Classify this taxa:",
                                              choices=levels(A$fac$Taxa),
                                              selected=NULL,
                                              multiple=FALSE,
                                              selectize=FALSE, size=20)),
                           h3("Training"), hr(),
                           h5("Total number of grains"),
                           verbatimTextOutput("classify_N_ref"),
                           h5("Per class"),
                           verbatimTextOutput("classify_N_ref_tab"),
                           h3("Classification"), hr(),
                           h5("Total number of  grains"),
                           verbatimTextOutput("classify_N_unk"),
                           h5("Per class"),
                           verbatimTextOutput("classify_counts"),
                           h5("Percentage per class"),
                           verbatimTextOutput("classify_pc"),
                           h5("Silhouette plot"), hr(),
                           em("Every vertical bar is a grain with
                              its posterior probability to
                              belong to one of the classes"),
                           dataTableOutput("classify_probs_fac"),
                           plotOutput("classify_plot")),
                  # Traditional ################################################
                  tabPanel("Traditional",
                           selectInput("trad_x",
                                       "x-axis",
                                       choices=c("NULL", colnames(A$fac)),
                                       selected="Width", multiple=FALSE),
                           selectInput("trad_y",
                                       "y-axis",
                                       choices=c("NULL", colnames(A$fac)),
                                       selected = "Length", multiple=FALSE),
                           selectInput("trad_col",
                                       "Color",
                                       choices=c("NULL", colnames(A$fac)),
                                       selected = "Period", multiple=FALSE),
                           selectInput("trad_shp",
                                       "Shape",
                                       choices=c("NULL", colnames(A$fac)),
                                       selected = "NULL", multiple=FALSE),
                           checkboxInput("trad_lm",
                                         "Add lm?", value = TRUE),
                           plotOutput("trad_plot")),
                  # Map ########################################################
                  tabPanel("Map",
                           plotOutput("plotMap")),
                  # Sample sizes ###############################################
                  tabPanel("Sample sizes",
                           column(3,
                                  h5("Taxa"), hr(),
                                  tableOutput("N_Taxa")),
                           column(4,
                                  h5("Period"), hr(),
                                  tableOutput("N_Period"),
                                  h5("Site"), hr(),
                                  tableOutput("N_Site")),
                           column(5,
                                  h5("Site_phase"), hr(),
                                  tableOutput("N_Site_phase")))
      )
    )
  )
)
)


# Launch the baby
app <- shinyApp(ui = ui, server = server)
runApp(app)

```

**Comment by vbonhomme** [comment]
# here we specify (in 1/12th) the width of the sidebar
      width=3),

should come just before 'main panel', because it specifies the
cosmetics (here width) of the sidebar.


2015-07-10 11:07 GMT+02:00 Michael Paul Wallace <notifications@github.com>:

> IV_GrMoEx - copy.R
>
> ################################################################################
> #                           Morpho Grain Explorer                              #
> ################################################################################
>
> ### Libraries
> # order matters.
> library(MASS)
> library(shiny)
> library(dplyr)
> library(Momocs)
> library(ggplot2)
> library(ggmap)
>
>
> ### Data import
> load("arch_ready.rda")
> # catch "meta-groups" groups
> dotted_cols <- colnames(A$fac)[grep(pattern = "\\.", colnames(A$fac))]
> # load the map
> # we prepare for the map`
> # center_coords <- c(mean(range(unique(A$fac$Long))), mean(range(unique(A$fac$Lat))))
> # crescent_map <- get_map(center_coords, zoom=6, maptype = "watercolor")
> # save(crescent_map, file="crescent_map.rda")
> load("crescent_map.rda")
>
> # Server #######################################################################
> server <- function(input, output) {
>
>   # cosmetics. because selectInput accepts characters only, not functions.
>   palette_deliver <- function(input){
>     switch(input,
>            "col_spring"=col_spring,
>            "col_summer"=col_summer,
>            "col_autumn"=col_autumn,
>            "col_qual"=col_qual,
>            "col_solarized"=col_solarized)
>   }
>
>   # reactive section ###########################################################
>   # observe any change concerning filtering and recalculate a PCA
>   Ap <- reactive({
>     A %>% at_least(input$fac1, input$N) %>%
>       filter(Taxa %in% input$Taxa, Site_phase %in% input$Site_phase) %>%
>       PCA()
>   })
>
>   # same thing for LDA
>   Al <- reactive({
>     if (is.null(input$fac2)) {
>       fac <- input$fac1
>     } else {
>       fac <- as.formula(paste("~", input$fac1, "+", input$fac2))
>     }
>     LDA(Ap(), fac, retain=0.99, verbose=FALSE)
>   })
>
>   # Used by the map counts how many grain per Site
>   df_count <- reactive({
>     select(Ap()$fac, Site, Lat, Long) %>%
>       count(Site, Lat, Long) %>%
>       ungroup()
>   })
>
>   # PCA ########################################################################
>   # produces the PCA plot (and make it savable)
>   make_PCA_plot <- function(){
>     if (is.null(input$fac2)) {
>       fac <- input$fac1
>     } else {
>       fac <- as.formula(paste("~", input$fac1, "+", input$fac2))
>     }
>     plot(Ap(),
>          fac = fac,
>          zoom=input$zoom, xax=input$xax, yax=input$yax,
>          palette=palette_deliver(input$palette),
>          morphospace = input$morphospace, pos.shp=input$pos.shp,
>          points=input$points, ellipses=input$ellipses,
>          ellipsesax=input$ellipsesax,
>          chull=input$chull)
>   }
>   # PCA and its plot
>   output$PCA_plot <- renderPlot({
>     make_PCA_plot()
>   },
>   width=exprToFunction(input$plot_width),
>   height=exprToFunction(input$plot_width))
>
>   # PCA saver
>   observeEvent(input$pdf, {
>     name <- paste0("saved_graphs/", input$pdfname, "_",
>                    strftime(Sys.time(), format="%Y-%m-%d-%H-%M-%S"), ".pdf")
>     pdf(name)
>     make_PCA_plot()
>     dev.off()
>     cat( " * graph saved as", name, "\n")
>   })
>
>   # Map ########################################################################
>   # plots a map of the fertile crescent (or its left horn)
>   output$plotMap <- renderPlot({
>     f2n <- function(x) as.numeric(as.character(x))
>     dfc <- mutate(df_count(),
>                   Site=as.character(Site),
>                   Lat=f2n(Lat),
>                   Long=f2n(Long),
>                   n=as.numeric(n))
>     gg <- ggmap(crescent_map, darken=c(3/4, color="#FFFFFF")) +
>       geom_point(data=dfc, aes(x=Long, y=Lat, size=n), fill="#000000", alpha=0.1, shape=16) +
>       scale_size_area(max_size = 25) +
>       geom_text(data=dfc, aes(x=Long, y=Lat, label=n), size=4) +
>       geom_text(data=dfc, aes(x=Long, y=Lat+0.25, label=Site), size=3) +
>       theme(legend.position="none")
>     suppressWarnings(print(gg))
>   },
>   width=exprToFunction(input$plot_width),
>   height=exprToFunction(input$plot_width))
>
>   output$dfc <- renderPrint(df_count())
>
>   # Sample sizes ###############################################################
>   output$N_Period <- renderTable(
>     select(Ap()$fac, Period) %>% count(Period) %>% arrange(desc(n))
>   )
>   output$N_Site <- renderTable({
>     select(Ap()$fac, Site) %>% count(Site) %>% arrange(desc(n))
>   })
>   output$N_Taxa <- renderTable(
>     select(Ap()$fac, Taxa) %>% count(Taxa) %>% arrange(desc(n))
>   )
>   output$N_Site_phase <- renderTable(
>     select(Ap()$fac, Site_phase) %>% count(Site_phase) %>% arrange(desc(n))
>   )
>
>   # LDA and its plot ###########################################################
>   output$LDA_plot <- renderPlot({
>     plot(Al(),
>          fac = fac,
>          zoom=input$zoom, xax=input$xax, yax=input$yax,
>          palette=palette_deliver(input$palette),
>          points=input$points, ellipses=input$ellipses,
>          ellipsesax=input$ellipsesax,
>          chull=input$chull)
>   },
>   width=exprToFunction(input$plot_width),
>   height=exprToFunction(input$plot_width))
>
>   # LDA confusion matrix
>   output$LDA_tab <- renderPlot({
>     gg <- plot_CV(Al(), freq=FALSE, rm0=TRUE, cex=3) + coord_equal()
>     print(gg)
>   },
>   width=exprToFunction(input$plot_width),
>   height=exprToFunction(input$plot_width))
>
>   # LDA % of correct classification
>   output$LDA_correct <- renderPrint({
>     print(round(Al()$CV.correct * 100), 1)
>   })
>
>   # % of correct classification per class
>   output$LDA_ce <- renderPrint({
>     print(round(Al()$CV.ce * 100, 1))
>   })
>
>   # Classify ###################################################################
>   make_silhouette <- function(){
>     probs <- classify()$probs
>     probs <- probs[order(probs[, 1], decreasing = TRUE), ]
>     cols <- col_qual(ncol(probs))
>     barplot(t(probs), names.arg=NULL, space=0,
>             col=cols, border=NA, axisnames=FALSE, xaxs="i")
>     legend("bottomleft", fill = cols, legend = colnames(probs), bty="n")
>   }
>
>   classify <- reactive({
>     # shortcut
>     ref <- input$classify_ref
>     unk <- input$classify_unk
>     # calculate a PCA using all taxa
>     P0 <- A %>%
>       filter(Taxa %in% c(ref, unk)) %>%
>       PCA()
>     # calculate an LDA using all but the unknown taxa
>     L0 <- P0 %>%
>       filter(Taxa != unk) %>%
>       LDA("Taxa", retain=0.99, verbose=FALSE)
>     # extract and prepare scores of the unknown taxa
>     P1_all <- P0 %>%
>       filter(Taxa == unk)
>     P1 <- P1_all$x[, 1:ncol(L0$x)]
>
>     # classify using the MASS::lda
>     pred <- predict(L0$mod, P1)
>
>     counts <- table(pred$class)
>     N_unk     <- sum(counts)
>     pc    <- round((counts / sum(counts))*100, 2)
>     probs <- pred$posterior
>     probs_fac <- cbind(pred$posterior, select(P1_all$fac, Site, Period)) %>%
>       group_by(Site, Period) %>%
>       summarise_each(funs(mean))
>     # not particularly clean
>     # probs_fac <- bind_cols(select(probs_fac, 1:2), round(select(probs_fac, 3)))
>
>     list(N_ref=nrow(L0$x),
>          N_ref_tab=table(L0$fac),
>          N_unk=N_unk,
>          counts=counts,
>          pc=pc,
>          probs=probs,
>          probs_fac=probs_fac)
>   })
>
>   output$classify_N_ref  <- renderPrint(classify()$N_ref)
>   output$classify_N_ref_tab  <- renderPrint(classify()$N_ref_tab)
>   output$classify_N_unk  <- renderPrint(classify()$N_unk)
>   output$classify_counts <- renderPrint(classify()$counts)
>   output$classify_pc     <- renderPrint(classify()$pc)
>   output$classify_probs_fac <- renderDataTable(classify()$probs_fac)
>   output$classify_plot   <- renderPlot(make_silhouette(),
>                                        width=exprToFunction(input$plot_width),
>                                        height=exprToFunction(input$plot_width))
>
>   # Traditional ################################################################
>   # bloody reactive
>   make_trad_plot <- function(){
>     f2n <- function(x) as.numeric(as.character(x))
>     dft <- mutate(Ap()$fac,
>                   Length=f2n(Length),
>                   Width=f2n(Width),
>                   Height=f2n(Height),
>                   BCstart=f2n(BCstart),
>                   BCmean=f2n(BCmean),
>                   BCend=f2n(BCend),
>                   Lat=f2n(Lat),
>                   Long=f2n(Long))
>
>     gg <- ggplot(data=dft) +
>       aes_string(x=input$trad_x, y=input$trad_y, col=input$trad_col, shp=input$trad_shp) +
>       geom_point()
>     if (input$trad_lm) gg <- gg + stat_smooth(method="lm")
>     print(gg)
>   }
>
>   output$trad_plot <- renderPlot(make_trad_plot(),
>                                  width=exprToFunction(input$plot_width),
>                                  height=exprToFunction(input$plot_width))
>
>   # output$trad2 <- renderPrint(summary(Ap()$fac))
>
> }
>
> # ui ###########################################################################
> # Define UI for random distribution application
> ui <- shinyUI(fluidPage(
>   ##### Title
>   titlePanel("GrMoEx"),
>   h6(paste("version", file.info("IV_GrMoEx.R")$mtime)),
>   sidebarLayout(
>     ##### Sidebar
>     sidebarPanel(
>       ### Cosmetics section
>       h3("Cosmetics"), hr(),
>       # plot width
>       sliderInput(inputId = "plot_width", label = "Plot width",
>                   min=200, max=1600, value=800, step = 100),
>       # plot zoom
>       sliderInput(inputId="zoom", label="zoom (<=1 to display all points)",
>                   min=0.1, max=5, value=1, step=0.1),
>       checkboxInput("points",
>                     label = "Add points",
>                     value = FALSE),
>       checkboxInput("ellipses",
>                     label = "Add (0.5) confidence ellipses",
>                     value = TRUE),
>       checkboxInput("ellipsesax",
>                     label = "Add (0.5, 0.75, 0.9) confidence ellipses axes",
>                     value = FALSE),
>       checkboxInput("chull",
>                     label = "Add convex hulls",
>                     value = FALSE),
>       checkboxInput("morphospace",
>                     label = "Display morphospace",
>                     value = TRUE),
>       selectInput("pos.shp",
>                   label = "Shape position",
>                   choices = list("full" = "full", "range" = "range", "xy"="xy"),
>                   selected = "full"),
>       # palette picker
>       selectInput("palette",
>                   label="Color palette",
>                   choices=list("col_spring", "col_summer", "col_autumn", "col_qual", "col_solarized"),
>                   selected="col_qual"),
>       # plot saver
>       textInput("pdfname", label = NULL, value = "Name"),
>       actionButton("pdf", "Save PCA plot"),
>       # here we specify (in 1/12th) the width of the sidebar
>       width=3),
>
>        ### Covariate section
>       h3("Covariates"), hr(),
>       # fac1
>       selectInput(inputId = "fac1",
>                   label="1st grouping factor to use:",
>                   choices=c("Taxa", dotted_cols,
>                             "Site", "Site_phase", "Region_coarse", "Region_fine",
>                             "Period", "BCstart", "BCend", "BCmean"),
>                   selected="Taxa",
>                   multiple=FALSE,
>                   selectize=FALSE),
>       # fac2
>       selectInput(inputId = "fac2",
>                   label="2nd grouping factor to use:",
>                   choices=c("NULL", "Taxa", dotted_cols,
>                             "Site", "Site_phase", "Region_coarse", "Region_fine",
>                             "Period", "BCstart", "BCend", "BCmean"),
>                   selected="NULL",
>                   multiple=FALSE,
>                   selectize=FALSE),
>
>       # axes selection
>       h5("PC axes to use"),
>       numericInput("xax", label = "Axis1", value = 1, 1, 10, 1),
>       numericInput("yax", label = "Axis", value = 2, 1, 10, 1),
>
>       ### Filtering section
>       h3("Filtering"), hr(),
>       # N in fac1 filtering
>       sliderInput("N",
>                   label="Min nb of grains per fac1",
>                   min=0, max=100, step=1, value=0),
>       p("'Ctrl'/'Cmd' is your friend below"),
>       # Taxa filtering
>       selectInput(inputId = "Taxa",
>                   label="Taxa to include:",
>                   choices=levels(A$fac$Taxa),
>                   selected=levels(A$fac$Taxa),
>                   multiple=TRUE, selectize=FALSE, size=20),
>       # Site filtering
>       selectInput(inputId = "Site_phase",
>                   label="Sites x Phase to include:",
>                   choices=levels(A$fac$Site_phase),
>                   selected=levels(A$fac$Site_phase),
>                   multiple=TRUE, selectize=FALSE, size=20),
>
>
>
>     ##### Main panel
>     mainPanel(
>       tabsetPanel(type = "pills",
>                   tabPanel("PCA",
>                            column(12,
>                                   plotOutput("PCA_plot"))),
>                   tabPanel("LDA plot",
>                            plotOutput("LDA_plot")),
>                   tabPanel("LDA CV",
>                            h5("% of correct classification"),
>                            verbatimTextOutput("LDA_correct"),
>                            h5("% of correct classification per class"),
>                            verbatimTextOutput("LDA_ce"),
>                            h5("Confusion matrix (CV leave-1-out)"),
>                            plotOutput("LDA_tab")),
>                   # Classify ###################################################
>                   tabPanel("Classify",
>                            column(6,
>                                   selectInput(inputId = "classify_ref",
>                                               label="Reference taxa:",
>                                               choices=levels(A$fac$Taxa),
>                                               selected=NULL,
>                                               multiple=TRUE,
>                                               selectize=FALSE, size=20)),
>                            column(6,
>                                   selectInput(inputId = "classify_unk",
>                                               label="Classify this taxa:",
>                                               choices=levels(A$fac$Taxa),
>                                               selected=NULL,
>                                               multiple=FALSE,
>                                               selectize=FALSE, size=20)),
>                            h3("Training"), hr(),
>                            h5("Total number of grains"),
>                            verbatimTextOutput("classify_N_ref"),
>                            h5("Per class"),
>                            verbatimTextOutput("classify_N_ref_tab"),
>                            h3("Classification"), hr(),
>                            h5("Total number of  grains"),
>                            verbatimTextOutput("classify_N_unk"),
>                            h5("Per class"),
>                            verbatimTextOutput("classify_counts"),
>                            h5("Percentage per class"),
>                            verbatimTextOutput("classify_pc"),
>                            h5("Silhouette plot"), hr(),
>                            em("Every vertical bar is a grain with
>                               its posterior probability to
>                               belong to one of the classes"),
>                            dataTableOutput("classify_probs_fac"),
>                            plotOutput("classify_plot")),
>                   # Traditional ################################################
>                   tabPanel("Traditional",
>                            selectInput("trad_x",
>                                        "x-axis",
>                                        choices=c("NULL", colnames(A$fac)),
>                                        selected="Width", multiple=FALSE),
>                            selectInput("trad_y",
>                                        "y-axis",
>                                        choices=c("NULL", colnames(A$fac)),
>                                        selected = "Length", multiple=FALSE),
>                            selectInput("trad_col",
>                                        "Color",
>                                        choices=c("NULL", colnames(A$fac)),
>                                        selected = "Period", multiple=FALSE),
>                            selectInput("trad_shp",
>                                        "Shape",
>                                        choices=c("NULL", colnames(A$fac)),
>                                        selected = "NULL", multiple=FALSE),
>                            checkboxInput("trad_lm",
>                                          "Add lm?", value = TRUE),
>                            plotOutput("trad_plot")),
>                   # Map ########################################################
>                   tabPanel("Map",
>                            plotOutput("plotMap")),
>                   # Sample sizes ###############################################
>                   tabPanel("Sample sizes",
>                            column(3,
>                                   h5("Taxa"), hr(),
>                                   tableOutput("N_Taxa")),
>                            column(4,
>                                   h5("Period"), hr(),
>                                   tableOutput("N_Period"),
>                                   h5("Site"), hr(),
>                                   tableOutput("N_Site")),
>                            column(5,
>                                   h5("Site_phase"), hr(),
>                                   tableOutput("N_Site_phase")))
>       )
>     )
>   )
> )
> )
>
>
> # Launch the baby
> app <- shinyApp(ui = ui, server = server)
> runApp(app)
>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/vbonhomme/GrMoEx/issues/16#issuecomment-120309351>.
>



-- 
vincentbonhomme.fr <http://www.vincentbonhomme.fr>

**Comment by MikePapaWhisky** [comment]
You lost me (sorry). Got time to implement it in the non-copy of IV?

**Comment by vbonhomme** [comment]
Done

**Comment by MikePapaWhisky** [comment]
Cheers. I'll try to figure out how you did when I get a moment (or five).

**Comment by vbonhomme** [comment]
the line:

width=3),

is expected to close the sidebarPanel group. but in your example you
moved it with all the cosmectics section


2015-07-10 11:25 GMT+02:00 Michael Paul Wallace <notifications@github.com>:

> Cheers. I'll try to figure out how you did when I get a moment (or five).
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/vbonhomme/GrMoEx/issues/16#issuecomment-120316440>.
>



-- 
vincentbonhomme.fr <http://www.vincentbonhomme.fr>
