### ISSUE TITLE
launch in browser by default?

### ISSUE THREAD

**Issue by vbonhomme** [vbonhomme/GrMoEx#17]
yes / no ?

**Comment by MikePapaWhisky** [comment]
You mean browser? What would be the motivation?

**Comment by vbonhomme** [comment]
dunno but there is an "open in browser" icon on top of embedded shiny popup
that I tend to use quite often

2015-07-10 14:51 GMT+02:00 Michael Paul Wallace <notifications@github.com>:

> You mean browser? What would be the motivation?
> On 10 Jul 2015 13:22, "Vincent Bonhomme" <notifications@github.com> wrote:
>
> > yes / no ?
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/vbonhomme/GrMoEx/issues/17>.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/vbonhomme/GrMoEx/issues/17#issuecomment-120402353>.
>



-- 
vincentbonhomme.fr <http://www.vincentbonhomme.fr>

**Comment by MikePapaWhisky** [comment]
I vote no.

**Comment by vbonhomme** [comment]
ok.

closes

2015-07-10 16:01 GMT+02:00 Michael Paul Wallace <notifications@github.com>:

> I vote no.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/vbonhomme/GrMoEx/issues/17#issuecomment-120416130>.
>



-- 
vincentbonhomme.fr <http://www.vincentbonhomme.fr>
