### ISSUE TITLE
Tboe-Sec[cfTboe-mono]

### ISSUE THREAD

**Issue by MikePapaWhisky** [vbonhomme/GrMoEx#19]
Where did that taxon come from? I think it appeared around the time we were discussing what to do with Tboe(cf). If it was something you created, could you roll it back to the previous taxon? I can't see where in the code you made the change to fix it myself. This shouldn't be a taxon we use, unless its something Emily came up with directly with you.

**Comment by vbonhomme** [comment]
2015-07-10 16:30 GMT+02:00 Michael Paul Wallace <notifications@github.com>:

> Where did that taxon come from?
>

from images (names)


> I think it appeared around the time we were discussing what to do with
> Tboe(cf). If it was something you created, could you roll it back to the
> previous taxon? I can't see where in the code you made the change to fix it
> myself. This shouldn't be a taxon we use, unless its something Emily came
> up with directly with you.
>

shall I just drop it in III_Prepare ?

> —
> Reply to this email directly or view it on GitHub
> <https://github.com/vbonhomme/GrMoEx/issues/19>.
>



-- 
vincentbonhomme.fr <http://www.vincentbonhomme.fr>

**Comment by vbonhomme** [comment]
done

**Comment by MikePapaWhisky** [comment]
So did ```Tboe-Sec[cfTboe-mono]``` become ```Tboe-Sec[cfTboe]```?
