### ISSUE TITLE
Min grains by fac1 and fac2

### ISSUE THREAD

**Issue by MikePapaWhisky** [vbonhomme/GrMoEx#20]
The minimum grains is there to make sure we don't include tiny groups, to that end if we're grouping by two variables we still want to be able to impose a minimum.

**Comment by vbonhomme** [comment]
Tricky one but done.

**Comment by MikePapaWhisky** [comment]
Thanks!



----------------------------------------------------------------
Dr Michael Wallace
Research Associate in Archaeobotany
Departmental Publicity & Marketing Officer

University of Sheffield, Department of Archaeology,
Northgate House, West Street, Sheffield, S1 4ET, UK.
Room 103 - SCALE
<https://www.sheffield.ac.uk/archaeology/research/scale> research
centre
+44 (0)114 22 22933

http://www.sheffield.ac.uk/archaeology/people/wallace
<http://www.shef.ac.uk/archaeology/people/wallace>
----------------------------------------------------------------
Sheffield Archaeology on Facebook
<http://www.facebook.com/ArchaeologySheffield> and YouTube
<http://www.youtube.com/ArchaeologyShef>
----------------------------------------------------------------
*Note I am employed part-time; normal workdays: Tues & Fri*.
