### ISSUE TITLE
Frequency table of site x phase x taxon

### ISSUE THREAD

**Issue by MikePapaWhisky** [vbonhomme/GrMoEx#21]
Not for implementation in GME. I'll produce it for Glynis.

**Comment by vbonhomme** [comment]
what do you mean ?

2015-07-10 17:09 GMT+02:00 Michael Paul Wallace <notifications@github.com>:

> Not for implementation in GME. I'll produce it for Glynis.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/vbonhomme/GrMoEx/issues/21>.
>



-- 
vincentbonhomme.fr <http://www.vincentbonhomme.fr>

**Comment by MikePapaWhisky** [comment]
Just there as a reminder for me. She's after a master list of sample sizes
for each site phase.

**Comment by vbonhomme** [comment]
I can add a reactive one at the bottom of Sample Size tab. Not a big deal
?

**Comment by vbonhomme** [comment]
Done

**Comment by vbonhomme** [comment]
remove 0s

**Comment by vbonhomme** [comment]
Fixed.

**Comment by MikePapaWhisky** [comment]
It was a matrix I wanted one, but don't worry its just something Glynis
wants once that she can print off to use as a reference sheet. Shouldn't
have put it on GitHub.



----------------------------------------------------------------
Dr Michael Wallace
Research Associate in Archaeobotany
Departmental Publicity & Marketing Officer

University of Sheffield, Department of Archaeology,
Northgate House, West Street, Sheffield, S1 4ET, UK.
Room 103 - SCALE
<https://www.sheffield.ac.uk/archaeology/research/scale> research
centre
+44 (0)114 22 22933

http://www.sheffield.ac.uk/archaeology/people/wallace
<http://www.shef.ac.uk/archaeology/people/wallace>
----------------------------------------------------------------
Sheffield Archaeology on Facebook
<http://www.facebook.com/ArchaeologySheffield> and YouTube
<http://www.youtube.com/ArchaeologyShef>
----------------------------------------------------------------
*Note I am employed part-time; normal workdays: Tues & Fri*.
