### ISSUE TITLE
Cosmetics back to bottom of side panel

### ISSUE THREAD

**Issue by MikePapaWhisky** [vbonhomme/GrMoEx#22]
Sorry...

**Comment by vbonhomme** [comment]
done #closes

2015-07-10 17:17 GMT+02:00 Michael Paul Wallace <notifications@github.com>:

> Sorry...
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/vbonhomme/GrMoEx/issues/22>.
>



-- 
vincentbonhomme.fr <http://www.vincentbonhomme.fr>
