### ISSUE TITLE
Minimise junk in side panel

### ISSUE THREAD

**Issue by MikePapaWhisky** [vbonhomme/GrMoEx#23]
We need the side panel to be as short as possible because scrolling down (and losing sight of the plot) is proving disruptive.

**Comment by vbonhomme** [comment]
no kidding!

* Tell me what to remove for good
* Or which items to put in tabs ?

2015-07-10 17:20 GMT+02:00 Michael Paul Wallace <notifications@github.com>:

> We need the side panel to be as short as possible because scrolling down
> (and losing sight of the plot) is proving disruptive.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/vbonhomme/GrMoEx/issues/23>.
>



-- 
vincentbonhomme.fr <http://www.vincentbonhomme.fr>

**Comment by MikePapaWhisky** [comment]
I guess there's a lot of white-space, can this be reduced? But more usefully, can we have tabs in side-panel? If so let's try having a Covariates, Filtering and Appearance (rather than Cosmetics, please) tab?

**Comment by vbonhomme** [comment]
did my best

**Comment by MikePapaWhisky** [comment]
Your best is better than all the rest.

**Comment by vbonhomme** [comment]
if you're ok to switch:
* covariates and filtering in their own tab
* PCA/LDA cosmetics within the PCA/LDA tabs
I can make this thing happen: http://rstudio.github.io/shinydashboard/ quite easily

**Comment by MikePapaWhisky** [comment]
Could give it a go. Going to be much work. If it is we'll manage OK with
the current side bar.

**Comment by vbonhomme** [comment]
ok gonna see after all the rest.
but gonna need it for shinyMomocs anyway :o)

± off until wed pm (got some family here), but if there is sth really
urgent let me know.



2015-07-13 15:12 GMT+02:00 Michael Paul Wallace <notifications@github.com>:

> Could give it a go. Going to be much work. If it is we'll manage OK with
> the current side bar.
> On 13 Jul 2015 13:03, "Vincent Bonhomme" <notifications@github.com> wrote:
>
> > if you're ok to switch:
> >
> > - covariates and filtering in their own tab
> > - PCA/LDA cosmetics within the PCA/LDA tabs I can make this thing
> > happen: http://rstudio.github.io/shinydashboard/ quite easily
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/vbonhomme/GrMoEx/issues/23#issuecomment-120903247>.
>
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/vbonhomme/GrMoEx/issues/23#issuecomment-120923326>.
>



-- 
vincentbonhomme.fr <http://www.vincentbonhomme.fr>

**Comment by MikePapaWhisky** [comment]
If you want to try it for ShinyMomocs go for it. Shouldn't need anything
urgent in next few days. Meeting Eleanor on Wed morning, but that's more
for traditional measurements.

**Comment by MikePapaWhisky** [comment]
By the way. Really like the axis and covariates as side-by-side. 
- [ ] We need to reduce the character length of the grouping variables though (are these pulled straight from column names in ```Sample phase dates.txt```?). 
- [x] Also, edited line 375 to ```label = "Add (0.5, 0.75, 0.9) conf. ellipses axes",``` so on one line
- [ ] You can remove and condense ```PC aces to use```

**Comment by vbonhomme** [comment]
- [x] You can remove and condense ```PC aces to use```

**Comment by vbonhomme** [comment]
- [ ] We need to reduce the character length of the grouping variables though (are these pulled straight from column names in ```Sample phase dates.txt```?). 

> what do you mean ?

**Comment by MikePapaWhisky** [comment]
Depending on the screen size the full factor name doesn't fit in the dropdown box. E.g. ```Region.coarse``` becomes ```Regi...arse```. I've had a look at the names, however, and can't think of shorter names - so we can forget about that last point.

**Comment by vbonhomme** [comment]
well we could use sth like this:

abbreviate(iris$Species)

 but the best option is to buy a new screen

2015-07-14 13:33 GMT+02:00 Michael Paul Wallace <notifications@github.com>:

> Depending on the screen size the full factor name doesn't fit in the
> dropdown box. E.g. Region.coarse becomes Regi...arse. I've had a look at
> the names, however, and can't think of shorter names - so we can forget
> about that last point.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/vbonhomme/GrMoEx/issues/23#issuecomment-121210370>.
>



-- 
vincentbonhomme.fr <http://www.vincentbonhomme.fr>
