### ISSUE TITLE
Sample size tab

### ISSUE THREAD

**Issue by MikePapaWhisky** [vbonhomme/GrMoEx#24]
As well as the overall summary on the Sample size tab. Could we have the same summary by grouping fac1 (fac2).

**Comment by vbonhomme** [comment]
* Shall I remove the first four then or are then always useful ? if fac1 =
Taxa we gonna have duplicate then... And quite a huge effort to make a
conditional panel.
* What do you mean by fac1 (fac2) ? fac1, fac2, and fac1 x fac2 ?

2015-07-10 17:25 GMT+02:00 Michael Paul Wallace <notifications@github.com>:

> As well as the overall summary on the Sample size tab. Could we have the
> same summary by grouping fac1 (fac2).
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/vbonhomme/GrMoEx/issues/24>.
>



-- 
vincentbonhomme.fr <http://www.vincentbonhomme.fr>

**Comment by MikePapaWhisky** [comment]
* The first four (i.e. sample sizes for everything currently selected on filter) is always useful.
* If fac1 is *Taxa* it will indeed duplicate the first section, but I don't think this is a problem - might not look gorgeous, but its only the functionality we're after
* Sorry should have been clearer, yes fac1 X fac2 (assuming fac2 != NULL)

The important point here is that at a glance we want to see what potential biases are in the whole active dataset and the groupings. We might see that there is, say, a regional difference between Southern and Northern Levant - but if we spot on the ```Sample size``` that the sites from the different regions are from different periods it might be a temporal rather than spatial pattern we're seeing. Basically we have a really shitty dataset.

**Comment by vbonhomme** [comment]
done
