### ISSUE TITLE
pdf saver(s)

### ISSUE THREAD

**Issue by vbonhomme** [vbonhomme/GrMoEx#25]
question: do you really need such feature everywhere ?

**Comment by vbonhomme** [comment]
ping

**Comment by MikePapaWhisky** [comment]
It hasn't come up as much as I thought it would with Glynis, so not as desperate as I once thought. I'm kind of thinking ahead of presenting our findings, and think once we're used to using GrMoEx it would be nice to getting plots out in a format that can be used in presentations. Is it going to be a tough one?

**Comment by vbonhomme** [comment]
not very though but long, painful and verbose.
would a right click on the plot be a nice alternative ?

2015-07-14 13:36 GMT+02:00 Michael Paul Wallace <notifications@github.com>:

> It hasn't come up as much as I thought it would with Glynis, so not as
> desperate as I once thought. I'm kind of thinking ahead of presenting our
> findings, and think once we're used to using GrMoEx it would be nice to
> getting plots out in a format that can be used in presentations. Is it
> going to be a tough one?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/vbonhomme/GrMoEx/issues/25#issuecomment-121210686>.
>



-- 
vincentbonhomme.fr <http://www.vincentbonhomme.fr>

**Comment by MikePapaWhisky** [comment]
Right-click on plot would be lovely and totally suffice if saves at sufficiently high resolution. I know this is a boring one, but just trying to think ahead - one day we might have some publishable archaeological findings.

**Comment by vbonhomme** [comment]
2015-07-14 13:53 GMT+02:00 Michael Paul Wallace <notifications@github.com>:

> Right-click on plot would be lovely and totally suffice if saves at
> sufficiently high resolution.
>

isnt it the case ?
if you open the app in a browser, then download the file rather than copy
it, that's pretty nice !?


> I know this is a boring one, but just trying to think ahead - one day we
> might have some publishable archaeological findings.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/vbonhomme/GrMoEx/issues/25#issuecomment-121214778>.
>



-- 
vincentbonhomme.fr <http://www.vincentbonhomme.fr>

**Comment by MikePapaWhisky** [comment]
Never even thought to try it. OK, let's leave it at that for now. (Apparently I can't close this issue).
