### ISSUE TITLE
Additional filter

### ISSUE THREAD

**Issue by MikePapaWhisky** [vbonhomme/GrMoEx#26]
I'm going to replace *period* in sample phase dates.CSV once that is done could you add Site X Period as a third filter option?

**Comment by vbonhomme** [comment]
sure. as long as you ask nicely.

2015-07-10 17:47 GMT+02:00 Michael Paul Wallace <notifications@github.com>:

> I'm going to replace *period* in sample phase dates.CSV once that is done
> could you add Site X Period as a third filter option?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/vbonhomme/GrMoEx/issues/26>.
>



-- 
vincentbonhomme.fr <http://www.vincentbonhomme.fr>

**Comment by vbonhomme** [comment]
just detail me what to do, my brain is melting.

**Comment by MikePapaWhisky** [comment]
https://www.youtube.com/watch?v=1l1VyrpvVFY

**Comment by vbonhomme** [comment]
Your first comment is not very clear to me. What do you want me to add ? One of the col Site Period form Sample phase dates ?

**Comment by MikePapaWhisky** [comment]
Going to do something with this tomorrow. I'll update the issue when I have
something for you.

**Comment by MikePapaWhisky** [comment]
OK. So this is a Glynis request. I'm not sure of the merits of it; but tell me what you think. 

We can currently filter individual taxa and site-phases (which is the lowest common denominator in terms of location and date). Can we add (so the other two remain) a third filter that can exclude/include samples based on their Period? 

***An example***
If *PPNA* was unticked in the new filter then in any samples with a site-phase that falls in the *PPNA* (as per ```database details.csv``` would be excluded). The filter would have to work in tandem with the current site-phase filter, such that it would be possible to exclude an entire period **and** individual site-phases from a different period. How achievable is that?

**Comment by vbonhomme** [comment]
well if we remove a certain period all site_phase within this period will
be removed thanks to the filtering of rows given the period column

is a green light to add a third one filtering box ?

2015-07-14 13:30 GMT+02:00 Michael Paul Wallace <notifications@github.com>:

> OK. So this is a Glynis request. I'm not sure of the merits of it; but
> tell me what you think.
>
> We can currently filter individual taxa and site-phases (which is the
> lowest common denominator in terms of location and date). Can we add (so
> the other two remain) a third filter that can exclude/include samples based
> on their Period?
>
> *An example*
> If *PPNA* was unticked in the new filter then in any samples with a
> site-phase that falls in the *PPNA* (as per database details.csv would be
> excluded). The filter would have to work in tandem with the current
> site-phase filter, such that it would be possible to exclude an entire
> period *and* individual site-phases from a different period. How
> achievable is that?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/vbonhomme/GrMoEx/issues/26#issuecomment-121209193>.
>



-- 
vincentbonhomme.fr <http://www.vincentbonhomme.fr>

**Comment by MikePapaWhisky** [comment]
Yes the site_phases with ```period == PPNA``` will obviously be removed if we exclude ```PPNA```, but we would still like to exclude individual site_phases for which ```period != PPNA```. Green light.

**Comment by vbonhomme** [comment]
done

**Comment by MikePapaWhisky** [comment]
Looks good
xx



----------------------------------------------------------------
Dr Michael Wallace
Research Associate in Archaeobotany
Departmental Publicity & Marketing Officer

University of Sheffield, Department of Archaeology,
Northgate House, West Street, Sheffield, S1 4ET, UK.
Room 103 - SCALE
<https://www.sheffield.ac.uk/archaeology/research/scale> research
centre
+44 (0)114 22 22933

http://www.sheffield.ac.uk/archaeology/people/wallace
<http://www.shef.ac.uk/archaeology/people/wallace>
----------------------------------------------------------------
Sheffield Archaeology on Facebook
<http://www.facebook.com/ArchaeologySheffield> and YouTube
<http://www.youtube.com/ArchaeologyShef>
----------------------------------------------------------------
*Note I am employed part-time; normal workdays: Tues & Fri*.
