### ISSUE TITLE
New periods in site phase dates.txt

### ISSUE THREAD

**Issue by MikePapaWhisky** [vbonhomme/GrMoEx#28]
Hi,
I've updated the ```Main Period``` column in ```Site phase dates.txt```. I've sourced III, but the update is still not reflected in GrMoEx. Where do I need to go to implement this change. 
NB: this is a precursor to dealing with [/26] (https://github.com/vbonhomme/GrMoEx/issues/26).

**Comment by vbonhomme** [comment]
works well by my side. the col is renamed 'Period'. See line #37 in
'III_Prepare.R'

2015-07-14 13:01 GMT+02:00 Michael Paul Wallace <notifications@github.com>:

> Hi,
> I've updated the Main Period column in Site phase dates.txt. I've sourced
> III, but the update is still not reflected in GrMoEx. Where do I need to go
> to implement this change.
> NB: this is a precursor to dealing with /26
> <https://github.com/vbonhomme/GrMoEx/issues/26>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/vbonhomme/GrMoEx/issues/28>.
>



-- 
vincentbonhomme.fr <http://www.vincentbonhomme.fr>

**Comment by MikePapaWhisky** [comment]
So is it ```database details.csv``` I need to edit rather than ```site phase dates.txt```? From a R-code perspective is the .txt file contributing in anyway; if not it can be deleted.

**Comment by MikePapaWhisky** [comment]
Resolved. Turns out I've been working on the wrong file for the last few days (sad face); should all be OK now.

**Comment by vbonhomme** [comment]
mentionned it somewhere but probably not very loud... my fault


2015-07-14 13:24 GMT+02:00 Michael Paul Wallace <notifications@github.com>:

> Resolved. Turns out I've been working on the wrong file for the last few
> days (sad face); should all be OK now.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/vbonhomme/GrMoEx/issues/28#issuecomment-121206496>.
>



-- 
vincentbonhomme.fr <http://www.vincentbonhomme.fr>
