### ISSUE TITLE
Confidence ellipse axes

### ISSUE THREAD

**Issue by MikePapaWhisky** [vbonhomme/GrMoEx#29]
I know the confidence ellipse axes get thinner with increased confidence, but the change in size is almost undetectable by eye on the plots. *This is really low priority as I don't think we're likely to use these often - but thought I'd mention in case it crops up for Shiny-Momocs*

**Comment by vbonhomme** [comment]
yeah. can be changed in the plot.PCA call eg: 
```conf_ellipsesax=c(0.5, 0.75, 0.9), lwd.ellipsesax=c(5, 3, 1)```
