### ISSUE TITLE
Rotated Polar views

### ISSUE THREAD

**Issue by MikePapaWhisky** [vbonhomme/GrMoEx#30]
Having looked at several of the PCA plots I'm fairly convinced that there is an issue in regards to some of the polar views are not properly aligned (i.e. the ventral face is not towards the bottom of the scree), and that this is influencing the PCAs. 

I can't help but feel the best solution is to go to the original silhouettes and manually rotate any that don't look right. 

Before I/Emily crack on with that do you (a) have any alternative solution, and (b) have any advice in regards to how we get the rotated outlines into the analysis (e.g. do we send you just the rotated silhouettes? Or do we run the analysis afresh on the full set of silhouettes?)?

**Comment by vbonhomme** [comment]
Let me first fix all in GrMoEx, today or tomorrow.
Then we gonna start everything polar views.



2015-07-14 13:57 GMT+02:00 Michael Paul Wallace <notifications@github.com>:

> Having looked at several of the PCA plots I'm fairly convinced that there
> is an issue in regards to some of the polar views are not properly aligned
> (i.e. the ventral face is not towards the bottom of the scree), and that
> this is influencing the PCAs.
>
> I can't help but feel the best solution is to go to the original
> silhouettes and manually rotate any that don't look right.
>
> Before I/Emily crack on with that do you (a) have any alternative
> solution, and (b) have any advice in regards to how we get the rotated
> outlines into the analysis (e.g. do we send you just the rotated
> silhouettes? Or do we run the analysis afresh on the full set of
> silhouettes?)?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/vbonhomme/GrMoEx/issues/30>.
>



-- 
vincentbonhomme.fr <http://www.vincentbonhomme.fr>

**Comment by vbonhomme** [comment]
if you dont mind

2015-07-14 14:02 GMT+02:00 Vincent Bonhomme <bonhomme.vincent@gmail.com>:

> Let me first fix all in GrMoEx, today or tomorrow.
> Then we gonna start everything polar views.
>
>
>
> 2015-07-14 13:57 GMT+02:00 Michael Paul Wallace <notifications@github.com>
> :
>
>> Having looked at several of the PCA plots I'm fairly convinced that there
>> is an issue in regards to some of the polar views are not properly aligned
>> (i.e. the ventral face is not towards the bottom of the scree), and that
>> this is influencing the PCAs.
>>
>> I can't help but feel the best solution is to go to the original
>> silhouettes and manually rotate any that don't look right.
>>
>> Before I/Emily crack on with that do you (a) have any alternative
>> solution, and (b) have any advice in regards to how we get the rotated
>> outlines into the analysis (e.g. do we send you just the rotated
>> silhouettes? Or do we run the analysis afresh on the full set of
>> silhouettes?)?
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/vbonhomme/GrMoEx/issues/30>.
>>
>
>
>
> --
> vincentbonhomme.fr <http://www.vincentbonhomme.fr>
>



-- 
vincentbonhomme.fr <http://www.vincentbonhomme.fr>

**Comment by vbonhomme** [comment]
"Having looked at several of the PCA plots I'm fairly convinced that there is an issue in regards to some of the polar views are not properly aligned (i.e. the ventral face is not towards the bottom of the scree), and that this is influencing the PCAs. "

could you please send me the options leading to a dubious morphospace ?

**Comment by vbonhomme** [comment]
not needed. see "polar.pdf" in the dropbox. quite a big mess even after the pipe (that's actually how efourier w/ norm=FALSE 'sees' the outlines)... before landmarking, let me investigate a couple of things.

**Comment by vbonhomme** [comment]
and all the GrMoEx results are thus dubious until we will have fixed that.

**Comment by vbonhomme** [comment]
fgProcrutes = fail

**Comment by vbonhomme** [comment]
see polar_rad.pdf = much better but still some grains are messing.
Momocs gained a coo_alignminradius method btw
gonna try to maximize bilateral symmetry

**Comment by emforster** [comment]
Hi, I've just put two (tiny - don't panic!) jpgs in the dropbox folder.  One is the original silhouette, other is rotated (suffix _ROT).  I can rotate all the polar views like this if necessary - I remember when we discussed this before, that the main issue was not  how long it would take to rotate them manually, but whether doing this has an impact on the scale (because photoshop sticks a big black box around it).  Or I'm happy to put a marker on them in a specific place if that's easier (e.g. middle of the 'top' or 'bottom' point).  I won't do anything until you've finished trying in GrMoEx though (VB) - -thanks!

**Comment by vbonhomme** [comment]
1. let me try a last thing on maximizyin bilat. symmetry
2. if we have to put two ldks, that can be done more easily (imageJ +
Momocs). will let you know


v

2015-07-15 17:04 GMT+02:00 emforster <notifications@github.com>:

> Hi, I've just put two (tiny - don't panic!) jpgs in the dropbox folder.
> One is the original silhouette, other is rotated (suffix _ROT). I can
> rotate all the polar views like this if necessary - I remember when we
> discussed this before, that the main issue was not how long it would take
> to rotate them manually, but whether doing this has an impact on the scale
> (because photoshop sticks a big black box around it). Or I'm happy to put a
> marker on them in a specific place if that's easier (e.g. middle of the
> 'top' or 'bottom' point). I won't do anything until you've finished trying
> in GrMoEx though (VB) - -thanks!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/vbonhomme/GrMoEx/issues/30#issuecomment-121645131>.
>



-- 
vincentbonhomme.fr <http://www.vincentbonhomme.fr>

**Comment by emforster** [comment]
Great - thanks either way!  :-)

**Comment by vbonhomme** [comment]
* maximizing bilateral symmetry = long and painful fail
* let's go for ldk then. would you prefer the Photoshop or the ImageJ+Momocs. Eventually, not sure that the second one is actually faster.

**Comment by emforster** [comment]
Ah - sounds nasty... I have a slight preference for photoshop as I use it a lot, but if it will be easier for you if I do it the other way, just let me know and tell me how you'd like it done.  Would one ldk on the top, mid-point do it? I can try a subset first if you want and see if that works. Thanks for trying to find a way around it!

**Comment by vbonhomme** [comment]
a subset of 10 seems nice.
ok by my side, dont worry.

photoshop option :
i think you can just orient black masks so that the top of the polar view
(ie the dorsal crest if you see what I mean) becomes the highest (in terms
of y-coordinates) with the deepest point of the ridge at the exact vertical
(downwards of it).

imageJ option:
as long as the mask have exactly the same coordinates as the intermediate
files (ie images are not resized), you can drag and drop jpg files in
ImageJ, select the "Multipoint tool" (on the left of the magic wand), click
on your two ldk (top, ridge), File > Save as XY coordinates, close your
file, then send me .txt generated.

2015-07-15 18:57 GMT+02:00 emforster <notifications@github.com>:

> Ah - sounds nasty... I have a slight preference for photoshop as I use it
> a lot, but if it will be easier for you if I do it the other way, just let
> me know and tell me how you'd like it done. Would one ldk on the top,
> mid-point do it? I can try a subset first if you want and see if that
> works. Thanks for trying to find a way around it!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/vbonhomme/GrMoEx/issues/30#issuecomment-121679134>.
>



-- 
vincentbonhomme.fr <http://www.vincentbonhomme.fr>

**Comment by emforster** [comment]
Thanks - I'll have a go at both as soon as I have a chance. Hope you are
having a good day!
Emily

On 15 July 2015 at 18:09, Vincent Bonhomme <notifications@github.com> wrote:

> a subset of 10 seems nice.
> ok by my side, dont worry.
>
> photoshop option :
> i think you can just orient black masks so that the top of the polar view
> (ie the dorsal crest if you see what I mean) becomes the highest (in terms
> of y-coordinates) with the deepest point of the ridge at the exact vertical
> (downwards of it).
>
> imageJ option:
> as long as the mask have exactly the same coordinates as the intermediate
> files (ie images are not resized), you can drag and drop jpg files in
> ImageJ, select the "Multipoint tool" (on the left of the magic wand), click
> on your two ldk (top, ridge), File > Save as XY coordinates, close your
> file, then send me .txt generated.
>
> 2015-07-15 18:57 GMT+02:00 emforster <notifications@github.com>:
>
> > Ah - sounds nasty... I have a slight preference for photoshop as I use it
> > a lot, but if it will be easier for you if I do it the other way, just
> let
> > me know and tell me how you'd like it done. Would one ldk on the top,
> > mid-point do it? I can try a subset first if you want and see if that
> > works. Thanks for trying to find a way around it!
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/vbonhomme/GrMoEx/issues/30#issuecomment-121679134>.
> >
>
>
>
> --
> vincentbonhomme.fr <http://www.vincentbonhomme.fr>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/vbonhomme/GrMoEx/issues/30#issuecomment-121681877>.
>



-- 
*Please consider the environment before printing this email or any
attachments*

Dr Emily Forster
PDRA in Archaeobotany and Associate University Teacher in Archaeopalynology
and Environmental Archaeology

University of Sheffield Department of Archaeology
Northgate House, West Street, Sheffield, S1 4ET
(if you are looking for me in the building I am in room 103)

E.E.Forster@sheffield.ac.uk
Tel: 01142222933
