### ISSUE TITLE
ggtree requirement for Clustering

### ISSUE THREAD

**Issue by MikePapaWhisky** [vbonhomme/GrMoEx#36]
On selecting the ```Clustering``` tab greeted by error requiring installation of ```ggtree```.
Added the following to IV (lines 28-34), if I've done something wrong please let me know:
```#source("http://bioconductor.org/biocLite.R")
#biocLite("Biostrings")
#source("http://bioconductor.org/biocLite.R")
#biocLite("EBImage")
library(Biostrings)
library(EBImage)
devtools::install_github('GuangchuangYu/ggtree')```

**Comment by MikePapaWhisky** [comment]
Now I've got this working it is _sweeeeet_

**Comment by vbonhomme** [comment]
the last version o fMomocs suggests the package rather than depends on it
(sensu DESCRIPTION file).
so I think that you just have to have the last version installed and ggtree
installed to make the thing work.
if not, tell me.

2015-07-24 15:25 GMT+02:00 Michael Paul Wallace <notifications@github.com>:

> Now I've got this working it is *sweeeeet*
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/vbonhomme/GrMoEx/issues/36#issuecomment-124519556>.
>



-- 
vincentbonhomme.fr <http://www.vincentbonhomme.fr>

**Comment by MikePapaWhisky** [comment]
Had latest Momocs, and those were the steps necessary foot ggtree.

**Comment by vbonhomme** [comment]
ok dude. thanks.

2015-07-24 16:14 GMT+02:00 Michael Paul Wallace <notifications@github.com>:

> Had latest Momocs, and those were the steps necessary foot ggtree.
> On 24 Jul 2015 14:28, "Vincent Bonhomme" <notifications@github.com> wrote:
>
> > the last version o fMomocs suggests the package rather than depends on it
> > (sensu DESCRIPTION file).
> > so I think that you just have to have the last version installed and
> ggtree
> > installed to make the thing work.
> > if not, tell me.
> >
> > 2015-07-24 15:25 GMT+02:00 Michael Paul Wallace <
> notifications@github.com
> > >:
> >
> > > Now I've got this working it is *sweeeeet*
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <https://github.com/vbonhomme/GrMoEx/issues/36#issuecomment-124519556
> >.
> > >
> >
> >
> >
> > --
> > vincentbonhomme.fr <http://www.vincentbonhomme.fr>
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/vbonhomme/GrMoEx/issues/36#issuecomment-124520589>.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/vbonhomme/GrMoEx/issues/36#issuecomment-124536780>.
>



-- 
vincentbonhomme.fr <http://www.vincentbonhomme.fr>
