### ISSUE TITLE
Default x-axis variable on Traditional

### ISSUE THREAD

**Issue by MikePapaWhisky** [vbonhomme/GrMoEx#39]
Super minor point. 
For the ```Traditional``` tab I'd like to have the X-axis set by default to ```BCmean```, as this is what we almost always use as the x-axis for these plots.
Rather than ask you I was using this as an excuse to go into the IV script to try and start working out how things work. I got as far as discovering the values for the x-axis have something to do with the ```trad_x``` object, but that's as far I got. You've done an awesome job at keeping the code clear and well labelled. I think GrMoEx is just too epic for a mere mortal like me though.

**Comment by vbonhomme** [comment]
a bit messy though.
see line 609 for the default value (already done)

**Comment by MikePapaWhisky** [comment]
So obvious! I don't know why I didn't see it. Just bamboozled by your awesomeness I guess.
