### ISSUE TITLE
Reconstruction labels

### ISSUE THREAD

**Issue by MikePapaWhisky** [vbonhomme/GrMoEx#41]
Hi,

There seems to be some mistakes in the reconstruction labels used for filtering (e.g. ```b/cc``` and two ```c```'s). Can you correct them from your end? I think they're all straight forwards.

Also in the covariates drop down mention can ```Rec``` please be replaced by ```Reconstruction```?

_P.S. Just demoed GrMoEx to Glynis and Eleanor - both very pleased with what they saw._

**Comment by vbonhomme** [comment]
Done. The new GrMoEx folder is the one I'm about to send. I gonna delete the old one.
