### ISSUE TITLE
GrMoEx location

### ISSUE THREAD

**Issue by MikePapaWhisky** [vbonhomme/GrMoEx#45]
Can I just confirm that the most up-to-date incarnation of GrMoEx and data that feeds into it are located in the folder:
```
Dropbox\GrMoEx
```
and not in the folder:
```
Dropbox\Origins shared (VB)\ArchFinal\GrMoEx
```

I think this is what we agreed. Would you mind deleting the defunct version of GrMoEx, as having two version just invites problems - as either me or Emily could attest to.

**Comment by vbonhomme** [comment]
it's at the root of my Dropbox folder. I have put a 'ThisFolder' file in
the current one.

2015-10-20 16:18 GMT+02:00 Michael Paul Wallace <notifications@github.com>:

> Can I just confirm that the most up-to-date incarnation of GrMoEx and data
> that feeds into it are located in the folder:
>
> and not in the folder:
> ```Dropbox\Origins shared (VB)\ArchFinal\GrMoEx```
>
> I think this is what we agreed. Would you mind deleting the defunct version of GrMoEx, as having two version just invites problems - as either me or Emily could attest to.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/vbonhomme/GrMoEx/issues/45>.
>



-- 
vincentbonhomme.fr <http://www.vincentbonhomme.fr>
