### ISSUE TITLE
Dorsal view

### ISSUE THREAD

**Issue by MikePapaWhisky** [vbonhomme/GrMoEx#47]
Dorsal views in the morphospace of GrMoEx are displayed with the longest dimension horizontal, and with the embryo to the left (the horizontal flip of the photograph from which the outline was derived).

Assuming this has no effect on the morphometric analysis, would you be able to rotate the dorsal view so that the longest dimension is vertical with the embryo at the bottom. This is the way dorsal views are traditionally depicted. 

It might not seem so important, but for those of us who don't study shape for a living it is easier to interpret a plot quickly if things appear as we expect them to. 

Hope that's not too much trouble superhero.

**Comment by vbonhomme** [comment]
as stated in the last thread, will include a rotation in plot.PCA

2015-10-20 17:35 GMT+02:00 Michael Paul Wallace <notifications@github.com>:

> Dorsal views in the morphospace of GrMoEx are displayed with the longest
> dimension horizontal, and with the embryo to the left (the horizontal flip
> of the photograph from which the outline was derived).
>
> Assuming this has no effect on the morphometric analysis, would you be
> able to rotate the dorsal view so that the longest dimension is vertical
> with the embryo at the bottom. This is the way dorsal views are
> traditionally depicted.
>
> It might not seem so important, but for those of us who don't study shape
> for a living it is easier to interpret a plot quickly if things appear as
> we expect them to.
>
> Hope that's not too much trouble superhero.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/vbonhomme/GrMoEx/issues/47>.
>



-- 
vincentbonhomme.fr <http://www.vincentbonhomme.fr>

**Comment by vbonhomme** [comment]
done
