### ISSUE TITLE
Label points with unique identifier 

### ISSUE THREAD

**Issue by MikePapaWhisky** [vbonhomme/GrMoEx#48]
We're repeatedly needing to refer back to the original photographs for outlines (depicted in the XY mode of morphospace) that appear unusual. At the moment there doesn't seem to be an easy way to identify the grain from which a outline was derived.

Do you think in addition to the ```Add points``` feature you could make an 'Add labels' which would add the unique identifier of the grain to the morphospace? This would ideally work in the combined views (d+l+p) as well as individual views.

**Comment by vbonhomme** [comment]
not a big deal. Would you be happy with just the 'id' column or something
else?

2015-10-20 17:40 GMT+02:00 Michael Paul Wallace <notifications@github.com>:

> We're repeatedly needing to refer back to the original photographs for
> outlines (depicted in the XY mode of morphospace) that appear unusual. At
> the moment there doesn't seem to be an easy way to identify the grain from
> which a outline was derived.
>
> Do you think in addition to the Add points feature you could make an 'Add
> labels' which would add the unique identifier of the grain to the
> morphospace? This would ideally work in the combined views (d+l+p) as well
> as individual views.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/vbonhomme/GrMoEx/issues/48>.
>



-- 
vincentbonhomme.fr <http://www.vincentbonhomme.fr>

**Comment by MikePapaWhisky** [comment]
Yeah. Great. ID should be the number at the start of the filename which is
unique to each grain (I.e. occurs three times, once for each view).
