### ISSUE TITLE
Lovely and pretty colourful outlines in morphospace

### ISSUE THREAD

**Issue by MikePapaWhisky** [vbonhomme/GrMoEx#49]
_You'll love this one. __Can you tell I'm back?___

So. When using the ```xy``` morphospace and a grouping factor. How about the silhouettes (presently all grey) adopt the colour of their grouping variable (the same colour that defines the points, convex hulls and ellipses)? Might be an easier way to look at patterns in grouping factors for smaller datasets.

> _Feel free to ignore Michael.
> He's a bit crazy._
- anon.

**Comment by vbonhomme** [comment]
shapes are reconstructed agnostically: they dont use the group information,
just the scores (position on the plane) compared to the mean shape (on the
origin) and  the rotation vector (from matrix diagonalization).

2015-10-20 17:46 GMT+02:00 Michael Paul Wallace <notifications@github.com>:

> *You'll love this one. Can you tell I'm back?*
>
> So. When using the xy morphospace and a grouping factor. How about the
> silhouettes (presently all grey) adopt the colour of their grouping
> variable (the same colour that defines the points, convex hulls and
> ellipses)? Might be an easier way to look at patterns in grouping factors
> for smaller datasets.
>
>
> *Feel free to ignore Michael. He's a bit crazy.*
>
>    - anon.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/vbonhomme/GrMoEx/issues/49>.
>



-- 
vincentbonhomme.fr <http://www.vincentbonhomme.fr>

**Comment by vbonhomme** [comment]
BUT, if you want a mean shape per group and not a regularl sampled
morphospace that could be feasible.

2015-10-20 18:35 GMT+02:00 Vincent Bonhomme <bonhomme.vincent@gmail.com>:

> shapes are reconstructed agnostically: they dont use the group
> information, just the scores (position on the plane) compared to the mean
> shape (on the origin) and  the rotation vector (from matrix
> diagonalization).
>
> 2015-10-20 17:46 GMT+02:00 Michael Paul Wallace <notifications@github.com>
> :
>
>> *You'll love this one. Can you tell I'm back?*
>>
>> So. When using the xy morphospace and a grouping factor. How about the
>> silhouettes (presently all grey) adopt the colour of their grouping
>> variable (the same colour that defines the points, convex hulls and
>> ellipses)? Might be an easier way to look at patterns in grouping factors
>> for smaller datasets.
>>
>>
>> *Feel free to ignore Michael. He's a bit crazy.*
>>
>>    - anon.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/vbonhomme/GrMoEx/issues/49>.
>>
>
>
>
> --
> vincentbonhomme.fr <http://www.vincentbonhomme.fr>
>



-- 
vincentbonhomme.fr <http://www.vincentbonhomme.fr>

**Comment by vbonhomme** [comment]
the two suggestions are there :
https://github.com/vbonhomme/Momocs/issues/99
I will try asap. probably tomorrow morning.
Try to think about something even more amzing for the issue #100 :o)

2015-10-20 18:35 GMT+02:00 Vincent Bonhomme <bonhomme.vincent@gmail.com>:

> BUT, if you want a mean shape per group and not a regularl sampled
> morphospace that could be feasible.
>
> 2015-10-20 18:35 GMT+02:00 Vincent Bonhomme <bonhomme.vincent@gmail.com>:
>
>> shapes are reconstructed agnostically: they dont use the group
>> information, just the scores (position on the plane) compared to the mean
>> shape (on the origin) and  the rotation vector (from matrix
>> diagonalization).
>>
>> 2015-10-20 17:46 GMT+02:00 Michael Paul Wallace <notifications@github.com
>> >:
>>
>>> *You'll love this one. Can you tell I'm back?*
>>>
>>> So. When using the xy morphospace and a grouping factor. How about the
>>> silhouettes (presently all grey) adopt the colour of their grouping
>>> variable (the same colour that defines the points, convex hulls and
>>> ellipses)? Might be an easier way to look at patterns in grouping factors
>>> for smaller datasets.
>>>
>>>
>>> *Feel free to ignore Michael. He's a bit crazy.*
>>>
>>>    - anon.
>>>
>>> —
>>> Reply to this email directly or view it on GitHub
>>> <https://github.com/vbonhomme/GrMoEx/issues/49>.
>>>
>>
>>
>>
>> --
>> vincentbonhomme.fr <http://www.vincentbonhomme.fr>
>>
>
>
>
> --
> vincentbonhomme.fr <http://www.vincentbonhomme.fr>
>



-- 
vincentbonhomme.fr <http://www.vincentbonhomme.fr>

**Comment by MikePapaWhisky** [comment]
It's OK. It would be more the shape(s) for each individual grain, anything
less wouldn't work. I was mainly seeing how far you would go to make me
happy.



----------------------------------------------------------------
Dr Michael Wallace
Research Associate in Archaeobotany
Departmental Publicity & Marketing Officer

University of Sheffield, Department of Archaeology,
Northgate House, West Street, Sheffield, S1 4ET, UK.
Room 103 - SCALE
<https://www.sheffield.ac.uk/archaeology/research/scale> research
centre
+44 (0)114 22 22933

http://www.sheffield.ac.uk/archaeology/people/wallace
<http://www.shef.ac.uk/archaeology/people/wallace>
----------------------------------------------------------------
Sheffield Archaeology on Facebook
<http://www.facebook.com/ArchaeologySheffield> and YouTube
<http://www.youtube.com/ArchaeologyShef>
----------------------------------------------------------------


*Please note I am employed part-time; normal workdays:Tues & Thurs
mornings, and Weds all day.*

**Comment by vbonhomme** [comment]
if you want individual morphospaces, try ```Shape position = xy```.
