### ISSUE TITLE
GrMoEx for polar views

### ISSUE THREAD

**Issue by vbonhomme** [vbonhomme/GrMoEx#5]
Basically, the same thing but for polar views only.
We will need to start back from outlines.

**Comment by MikePapaWhisky** [comment]
Do you have the Polar outlines, or do you need them from Emily?

**Comment by vbonhomme** [comment]
yes. a want to fix everything postCoe on GrMoEx first.

2015-07-14 13:50 GMT+02:00 Michael Paul Wallace <notifications@github.com>:

> Do you have the Polar outlines, or do you need them from Emily?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/vbonhomme/GrMoEx/issues/5#issuecomment-121213740>.
>



-- 
vincentbonhomme.fr <http://www.vincentbonhomme.fr>

**Comment by vbonhomme** [comment]
we now have a filtering per views in GrMoEx.
it uses the brand new method 'dissolve' and thus requires a Momocs update from GitHub.
Note that this filtering only applies on the grains for which we had 3 views, and do not encompass all available data.

**Comment by MikePapaWhisky** [comment]
So how do we move to adding all polar views (not just those that also have
L & D views) when polar is selected?



----------------------------------------------------------------
Dr Michael Wallace
Research Associate in Archaeobotany
Departmental Publicity & Marketing Officer

University of Sheffield, Department of Archaeology,
Northgate House, West Street, Sheffield, S1 4ET, UK.
Room 103 - SCALE
<https://www.sheffield.ac.uk/archaeology/research/scale> research
centre
+44 (0)114 22 22933

http://www.sheffield.ac.uk/archaeology/people/wallace
<http://www.shef.ac.uk/archaeology/people/wallace>
----------------------------------------------------------------
Sheffield Archaeology on Facebook
<http://www.facebook.com/ArchaeologySheffield> and YouTube
<http://www.youtube.com/ArchaeologyShef>
----------------------------------------------------------------
*Note I am employed part-time; normal workdays: Tues & Fri*.

**Comment by vbonhomme** [comment]
She is on it.

**Comment by vbonhomme** [comment]
Gonna do it today

**Comment by vbonhomme** [comment]
done and working locally but waiting for all polars being nicely landmarked to implement it.

**Comment by MikePapaWhisky** [comment]
Hi,
Have you had all of the landmarks from Emily (she says she sent them :-)), and is this issue now resolved?

**Comment by vbonhomme** [comment]
I think so. but nobody tried extensively since then anyway :/

2015-10-14 11:54 GMT+02:00 Michael Paul Wallace <notifications@github.com>:

> Hi,
> Have you had all of the landmarks from Emily (she says she sent them :-)),
> and is this issue now resolved?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/vbonhomme/GrMoEx/issues/5#issuecomment-147994901>.
>



-- 
vincentbonhomme.fr <http://www.vincentbonhomme.fr>
