### ISSUE TITLE
Minimum sample size slider not working correctly

### ISSUE THREAD

**Issue by MikePapaWhisky** [vbonhomme/GrMoEx#50]
We have found a scenario where a factor 1 group has a smaller sample size than the minimum sample size. Suggests there is a flaw in the filtering by minimum sample size.

E.g.
Select all taxa beginning HDIS or HHEX
Set factor 1 as Site-Phase
Set minimum sample size as 10
One of the include Site-Phases has a sample size of 8

**Comment by vbonhomme** [comment]
had a problem of precedence between a at_least command and later filtering.
now the at_least is done after all ohters filtering. GrMoEx version
03/11/15 12:49 + Momocs version 0.9.43 fixes it.

2015-11-03 11:45 GMT+01:00 Michael Paul Wallace <notifications@github.com>:

> We have found a scenario where a factor 1 group has a smaller sample size
> than the minimum sample size. Suggests there is a flaw in the filtering by
> minimum sample size.
>
> E.g.
> Select all taxa beginning HDIS or HHEX
> Set factor 1 as Site-Phase
> Set minimum sample size as 10
> One of the include Site-Phases has a sample size of 8
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/vbonhomme/GrMoEx/issues/50>.
>



-- 
vincentbonhomme.fr <http://www.vincentbonhomme.fr>

**Comment by MikePapaWhisky** [comment]
Super
