### ISSUE TITLE
Text size of labels

### ISSUE THREAD

**Issue by MikePapaWhisky** [vbonhomme/GrMoEx#51]
I'd like to have the text for labels on the PCA (e.g. for unique identifiers) to be a little larger in size. Can we increase it bit - probably not worth introducing a slider option. I'm assuming its somewhere around line 140 of IV but I'm not confident enough to make changes myself.

**Comment by vbonhomme** [comment]
you're right though ! increased a bit, but you can do it yourselft line 149:

```         cex.labelspoints = 0.75,```
