### ISSUE TITLE
align polar views

### ISSUE THREAD

**Issue by vbonhomme** [vbonhomme/GrMoEx#53]
area approach is not satisfactory, so try a procrustes + flipping

**Comment by vbonhomme** [comment]
done and included in the last version.
check in the root folder for two pdfs: polar_raw and polar_aligned. polar_raw is only area, polar_aligned is polar_raw + procrustes/flipping.

**Comment by vbonhomme** [comment]
plus the polar view morphospace in GrMoEx appears less dubious to me. let me know what do you guys think.

**Comment by vbonhomme** [comment]
all of this running on: 
```
GrMoEx version 09/11/15 08:55
Momocs version 0.9.45
```

**Comment by MikePapaWhisky** [comment]
polar_aligned.pdf looks pretty good (all polars upsode down again, though).
Alignment looks perfect. Most looked flipped the same way (right, or left
if rotated the correct way) - but there are a few exceptions. I'll try to
get Glynis to sit down and indicate all the ones she has an issue with.



----------------------------------------------------------------
Dr Michael Wallace
Research Associate in Archaeobotany
Departmental Publicity & Marketing Officer

University of Sheffield, Department of Archaeology,
Northgate House, West Street, Sheffield, S1 4ET, UK.
Room 103 - SCALE
<https://www.sheffield.ac.uk/archaeology/research/scale> research
centre
+44 (0)114 22 22933

http://www.sheffield.ac.uk/archaeology/people/wallace
<http://www.shef.ac.uk/archaeology/people/wallace>
----------------------------------------------------------------
Sheffield Archaeology on Facebook
<http://www.facebook.com/ArchaeologySheffield> and YouTube
<http://www.youtube.com/ArchaeologyShef>
----------------------------------------------------------------


*Please note I am employed part-time; normal workdays:Tues & Thurs
mornings, and Weds all day.*

**Comment by vbonhomme** [comment]
good. what do you mean upside down?

2015-11-10 11:38 GMT+01:00 Michael Paul Wallace <notifications@github.com>:

> polar_aligned.pdf looks pretty good (all polars upsode down again, though).
> Alignment looks perfect. Most looked flipped the same way (right, or left
> if rotated the correct way) - but there are a few exceptions. I'll try to
> get Glynis to sit down and indicate all the ones she has an issue with.
>
>
>
> ----------------------------------------------------------------
> Dr Michael Wallace
> Research Associate in Archaeobotany
> Departmental Publicity & Marketing Officer
>
> University of Sheffield, Department of Archaeology,
> Northgate House, West Street, Sheffield, S1 4ET, UK.
> Room 103 - SCALE
> <https://www.sheffield.ac.uk/archaeology/research/scale> research
> centre
> +44 (0)114 22 22933
>
> http://www.sheffield.ac.uk/archaeology/people/wallace
> <http://www.shef.ac.uk/archaeology/people/wallace>
> ----------------------------------------------------------------
> Sheffield Archaeology on Facebook
> <http://www.facebook.com/ArchaeologySheffield> and YouTube
> <http://www.youtube.com/ArchaeologyShef>
> ----------------------------------------------------------------
>
>
> *Please note I am employed part-time; normal workdays:Tues & Thurs
> mornings, and Weds all day.*
>
> On 9 November 2015 at 09:26, Vincent Bonhomme <notifications@github.com>
> wrote:
>
> > all of this running on:
> >
> > GrMoEx version 09/11/15 08:55
> > Momocs version 0.9.45
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/vbonhomme/GrMoEx/issues/53#issuecomment-155006853>.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/vbonhomme/GrMoEx/issues/53#issuecomment-155384626>.
>



-- 
vincentbonhomme.fr <http://www.vincentbonhomme.fr>

**Comment by MikePapaWhisky** [comment]
The ventral groove (the bum cheeks and crack) should always be depicted at
the bottom of the image (they're currently at the top).



----------------------------------------------------------------
Dr Michael Wallace
Research Associate in Archaeobotany
Departmental Publicity & Marketing Officer

University of Sheffield, Department of Archaeology,
Northgate House, West Street, Sheffield, S1 4ET, UK.
Room 103 - SCALE
<https://www.sheffield.ac.uk/archaeology/research/scale> research
centre
+44 (0)114 22 22933

http://www.sheffield.ac.uk/archaeology/people/wallace
<http://www.shef.ac.uk/archaeology/people/wallace>
----------------------------------------------------------------
Sheffield Archaeology on Facebook
<http://www.facebook.com/ArchaeologySheffield> and YouTube
<http://www.youtube.com/ArchaeologyShef>
----------------------------------------------------------------


*Please note I am employed part-time; normal workdays:Tues & Thurs
mornings, and Weds all day.*

**Comment by MikePapaWhisky** [comment]
Just shown this to Glynis. Won't have time to look in detail today. But a
bit of feedback:
(1) Would you generate a third plot which does the Procrustes flipping
WITHOUT first doing the area flipping
(2) what are the basis of the colours - assuming taxa from filename
(3) could we have species specific (not taxa specific) panels - perhaps if
you can write me a simple bit of code I can figure out
(4) are these the actual silhouette outlines, or reconstructed from the PCA
(assuming the former)

M



----------------------------------------------------------------
Dr Michael Wallace
Research Associate in Archaeobotany
Departmental Publicity & Marketing Officer

University of Sheffield, Department of Archaeology,
Northgate House, West Street, Sheffield, S1 4ET, UK.
Room 103 - SCALE
<https://www.sheffield.ac.uk/archaeology/research/scale> research
centre
+44 (0)114 22 22933

http://www.sheffield.ac.uk/archaeology/people/wallace
<http://www.shef.ac.uk/archaeology/people/wallace>
----------------------------------------------------------------
Sheffield Archaeology on Facebook
<http://www.facebook.com/ArchaeologySheffield> and YouTube
<http://www.youtube.com/ArchaeologyShef>
----------------------------------------------------------------


*Please note I am employed part-time; normal workdays:Tues & Thurs
mornings, and Weds all day.*

**Comment by vbonhomme** [comment]
see line 163 ```c(-pi/2, 0, -pi/2)``` for dorsal, lateral and polar views
respectively.

2015-11-10 12:35 GMT+01:00 Michael Paul Wallace <notifications@github.com>:

> The ventral groove (the bum cheeks and crack) should always be depicted at
> the bottom of the image (they're currently at the top).
>
>
>
> ----------------------------------------------------------------
> Dr Michael Wallace
> Research Associate in Archaeobotany
> Departmental Publicity & Marketing Officer
>
> University of Sheffield, Department of Archaeology,
> Northgate House, West Street, Sheffield, S1 4ET, UK.
> Room 103 - SCALE
> <https://www.sheffield.ac.uk/archaeology/research/scale> research
> centre
> +44 (0)114 22 22933
>
> http://www.sheffield.ac.uk/archaeology/people/wallace
> <http://www.shef.ac.uk/archaeology/people/wallace>
> ----------------------------------------------------------------
> Sheffield Archaeology on Facebook
> <http://www.facebook.com/ArchaeologySheffield> and YouTube
> <http://www.youtube.com/ArchaeologyShef>
> ----------------------------------------------------------------
>
>
> *Please note I am employed part-time; normal workdays:Tues & Thurs
> mornings, and Weds all day.*
>
> On 10 November 2015 at 10:46, Vincent Bonhomme <notifications@github.com>
> wrote:
>
>
> > good. what do you mean upside down?
> >
> > 2015-11-10 11:38 GMT+01:00 Michael Paul Wallace <
> notifications@github.com
> > >:
> >
> > > polar_aligned.pdf looks pretty good (all polars upsode down again,
> > though).
> > > Alignment looks perfect. Most looked flipped the same way (right, or
> left
> > > if rotated the correct way) - but there are a few exceptions. I'll try
> to
> > > get Glynis to sit down and indicate all the ones she has an issue with.
> > >
> > >
> > >
> > > ----------------------------------------------------------------
> > > Dr Michael Wallace
> > > Research Associate in Archaeobotany
> > > Departmental Publicity & Marketing Officer
> > >
> > > University of Sheffield, Department of Archaeology,
> > > Northgate House, West Street, Sheffield, S1 4ET, UK.
> > > Room 103 - SCALE
> > > <https://www.sheffield.ac.uk/archaeology/research/scale> research
> > > centre
> > > +44 (0)114 22 22933
> > >
> > > http://www.sheffield.ac.uk/archaeology/people/wallace
> > > <http://www.shef.ac.uk/archaeology/people/wallace>
> > > ----------------------------------------------------------------
> > > Sheffield Archaeology on Facebook
> > > <http://www.facebook.com/ArchaeologySheffield> and YouTube
> > > <http://www.youtube.com/ArchaeologyShef>
> > > ----------------------------------------------------------------
> > >
> > >
> > > *Please note I am employed part-time; normal workdays:Tues & Thurs
> > > mornings, and Weds all day.*
> > >
> > > On 9 November 2015 at 09:26, Vincent Bonhomme <
> notifications@github.com>
> > > wrote:
> > >
> > > > all of this running on:
> > > >
> > > > GrMoEx version 09/11/15 08:55
> > > > Momocs version 0.9.45
> > > >
> > > > —
> > > > Reply to this email directly or view it on GitHub
> > > > <
> https://github.com/vbonhomme/GrMoEx/issues/53#issuecomment-155006853
> > >.
> > > >
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <https://github.com/vbonhomme/GrMoEx/issues/53#issuecomment-155384626
> >.
> > >
> >
> >
> >
> > --
> > vincentbonhomme.fr <http://www.vincentbonhomme.fr>
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/vbonhomme/GrMoEx/issues/53#issuecomment-155386328>.
>
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/vbonhomme/GrMoEx/issues/53#issuecomment-155396243>.
>



-- 
vincentbonhomme.fr <http://www.vincentbonhomme.fr>

**Comment by vbonhomme** [comment]
2015-11-10 12:47 GMT+01:00 Michael Paul Wallace <notifications@github.com>:

> Just shown this to Glynis. Won't have time to look in detail today. But a
> bit of feedback:
> (1) Would you generate a third plot which does the Procrustes flipping
> WITHOUT first doing the area flipping
>

quite huge work but I'll do it.


> (2) what are the basis of the colours - assuming taxa from filename
>

nothing but qualitative colors to discriminate fac1


> (3) could we have species specific (not taxa specific) panels - perhaps if
> you can write me a simple bit of code I can figure out
>

dont understand


> (4) are these the actual silhouette outlines, or reconstructed from the PCA
> (assuming the former)
>

morphospaces are always reconstructed from PCA

>
> M
>
>
>
> ----------------------------------------------------------------
> Dr Michael Wallace
> Research Associate in Archaeobotany
> Departmental Publicity & Marketing Officer
>
> University of Sheffield, Department of Archaeology,
> Northgate House, West Street, Sheffield, S1 4ET, UK.
> Room 103 - SCALE
> <https://www.sheffield.ac.uk/archaeology/research/scale> research
> centre
> +44 (0)114 22 22933
>
> http://www.sheffield.ac.uk/archaeology/people/wallace
> <http://www.shef.ac.uk/archaeology/people/wallace>
> ----------------------------------------------------------------
> Sheffield Archaeology on Facebook
> <http://www.facebook.com/ArchaeologySheffield> and YouTube
> <http://www.youtube.com/ArchaeologyShef>
> ----------------------------------------------------------------
>
>
> *Please note I am employed part-time; normal workdays:Tues & Thurs
> mornings, and Weds all day.*
>
> On 10 November 2015 at 11:34, Michael Wallace <m.p.wallace@sheffield.ac.uk
> >
> wrote:
>
>
> > The ventral groove (the bum cheeks and crack) should always be depicted
> at
> > the bottom of the image (they're currently at the top).
> >
> >
> >
> > ----------------------------------------------------------------
> > Dr Michael Wallace
> > Research Associate in Archaeobotany
> > Departmental Publicity & Marketing Officer
> >
> > University of Sheffield, Department of Archaeology,
> > Northgate House, West Street, Sheffield, S1 4ET, UK.
> > Room 103 - SCALE <https://www.sheffield.ac.uk/archaeology/research/scale>
> research
> > centre
> > +44 (0)114 22 22933
> >
> > http://www.sheffield.ac.uk/archaeology/people/wallace
> > <http://www.shef.ac.uk/archaeology/people/wallace>
> > ----------------------------------------------------------------
> > Sheffield Archaeology on Facebook
> > <http://www.facebook.com/ArchaeologySheffield> and YouTube
> > <http://www.youtube.com/ArchaeologyShef>
> > ----------------------------------------------------------------
> >
> >
> > *Please note I am employed part-time; normal workdays:Tues & Thurs
> > mornings, and Weds all day.*
> >
> > On 10 November 2015 at 10:46, Vincent Bonhomme <notifications@github.com
> >
> > wrote:
> >
> >> good. what do you mean upside down?
> >>
> >> 2015-11-10 11:38 GMT+01:00 Michael Paul Wallace <
> notifications@github.com
> >> >:
> >>
> >> > polar_aligned.pdf looks pretty good (all polars upsode down again,
> >> though).
> >> > Alignment looks perfect. Most looked flipped the same way (right, or
> >> left
> >> > if rotated the correct way) - but there are a few exceptions. I'll try
> >> to
> >> > get Glynis to sit down and indicate all the ones she has an issue
> with.
> >> >
> >> >
> >> >
> >> > ----------------------------------------------------------------
> >> > Dr Michael Wallace
> >> > Research Associate in Archaeobotany
> >> > Departmental Publicity & Marketing Officer
> >> >
> >> > University of Sheffield, Department of Archaeology,
> >> > Northgate House, West Street, Sheffield, S1 4ET, UK.
> >> > Room 103 - SCALE
> >> > <https://www.sheffield.ac.uk/archaeology/research/scale> research
> >> > centre
> >> > +44 (0)114 22 22933
> >> >
> >> > http://www.sheffield.ac.uk/archaeology/people/wallace
> >> > <http://www.shef.ac.uk/archaeology/people/wallace>
> >> > ----------------------------------------------------------------
> >> > Sheffield Archaeology on Facebook
> >> > <http://www.facebook.com/ArchaeologySheffield> and YouTube
> >> > <http://www.youtube.com/ArchaeologyShef>
> >> > ----------------------------------------------------------------
> >> >
> >> >
> >> > *Please note I am employed part-time; normal workdays:Tues & Thurs
> >> > mornings, and Weds all day.*
> >> >
> >> > On 9 November 2015 at 09:26, Vincent Bonhomme <
> notifications@github.com
> >> >
> >> > wrote:
> >> >
> >> > > all of this running on:
> >> > >
> >> > > GrMoEx version 09/11/15 08:55
> >> > > Momocs version 0.9.45
> >> > >
> >> > > —
> >> > > Reply to this email directly or view it on GitHub
> >> > > <
> https://github.com/vbonhomme/GrMoEx/issues/53#issuecomment-155006853
> >> >.
> >> > >
> >> >
> >> > —
> >> > Reply to this email directly or view it on GitHub
> >> > <https://github.com/vbonhomme/GrMoEx/issues/53#issuecomment-155384626
> >.
> >> >
> >>
> >>
> >>
> >> --
> >> vincentbonhomme.fr <http://www.vincentbonhomme.fr>
> >>
> >> —
> >> Reply to this email directly or view it on GitHub
> >> <https://github.com/vbonhomme/GrMoEx/issues/53#issuecomment-155386328>.
> >>
> >
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/vbonhomme/GrMoEx/issues/53#issuecomment-155398481>.
>



-- 
vincentbonhomme.fr <http://www.vincentbonhomme.fr>

**Comment by MikePapaWhisky** [comment]
cheers



----------------------------------------------------------------
Dr Michael Wallace
Research Associate in Archaeobotany
Departmental Publicity & Marketing Officer

University of Sheffield, Department of Archaeology,
Northgate House, West Street, Sheffield, S1 4ET, UK.
Room 103 - SCALE
<https://www.sheffield.ac.uk/archaeology/research/scale> research
centre
+44 (0)114 22 22933

http://www.sheffield.ac.uk/archaeology/people/wallace
<http://www.shef.ac.uk/archaeology/people/wallace>
----------------------------------------------------------------
Sheffield Archaeology on Facebook
<http://www.facebook.com/ArchaeologySheffield> and YouTube
<http://www.youtube.com/ArchaeologyShef>
----------------------------------------------------------------


*Please note I am employed part-time; normal workdays:Tues & Thurs
mornings, and Weds all day.*

**Comment by vbonhomme** [comment]
you now have two concurrent PCAs and a radio button to select.
Note that:
* such huge changes are not easily handled with GrMoEx which is a bit too high level for that. All of this should have been noticed and fixed much before, but anyway.
* changes are not so crazy between the two alignments approaches.

**Comment by vbonhomme** [comment]
```
GrMoEx version 12/11/15 10:20
Momocs version 0.9.45
```
