### ISSUE TITLE
Choice of ellipse size

### ISSUE THREAD

**Issue by MikePapaWhisky** [vbonhomme/GrMoEx#54]
The default 0.5 ellipses are OK, but it would be nice to have the option of 0.75 and 0.9 ellipses too,

The ellipse axes, whilst meant to show this, are not much use because its usually impossible to resolve the different line thickness. Also axes are less intuitive to read than ellipses.

**Comment by vbonhomme** [comment]
fixed.
ellipsesax is now and additional confidence indicator (eg you can choose one conf for ellipses, and another for axis)
