### ISSUE TITLE
Lowest menu drop-down box unreadable

### ISSUE THREAD

**Issue by MikePapaWhisky** [vbonhomme/GrMoEx#56]
The drop-down menu for the lowest option in side panel hangs off the edge of the window (beyond the scroll limit). This was palette_picker, meaning it was difficult to switch palettes. As a temporary fix I have swapped with order of palette_picker and shape_position, but a more permanent solution might be to add white space at the bottom of the menu.

**Comment by vbonhomme** [comment]
fixed (I hope so, since I didnt have the problem myself, perhaps thanks to your patch).

**Comment by MikePapaWhisky** [comment]
Looks good. The lowermost two options are now sliders anyway, so its not a
problem due to the arrangement.



----------------------------------------------------------------
Dr Michael Wallace
Research Associate in Archaeobotany
Departmental Publicity & Marketing Officer

University of Sheffield, Department of Archaeology,
Northgate House, West Street, Sheffield, S1 4ET, UK.
Room 103 - SCALE
<https://www.sheffield.ac.uk/archaeology/research/scale> research
centre
+44 (0)114 22 22933

http://www.sheffield.ac.uk/archaeology/people/wallace
<http://www.shef.ac.uk/archaeology/people/wallace>
----------------------------------------------------------------
Sheffield Archaeology on Facebook
<http://www.facebook.com/ArchaeologySheffield> and YouTube
<http://www.youtube.com/ArchaeologyShef>
----------------------------------------------------------------


*Please note I am employed part-time; normal workdays:Tues & Thurs
mornings, and Weds all day.*
