### ISSUE TITLE
Solid symbols

### ISSUE THREAD

**Issue by MikePapaWhisky** [vbonhomme/GrMoEx#57]
Most of the time we will be comparing two to five groups, can you set things up so that the ````pch```` palette to return solid symbols for the first five, after this they can vary in anyway. The first two symbols presently are open triangle and cross (another form of open symbol).

**Comment by vbonhomme** [comment]
turned all of them to ```pch=20```. this option bothered me as well. will be removed in a further Momocs version: see https://github.com/vbonhomme/Momocs/issues/116

**Comment by MikePapaWhisky** [comment]
Having different symbols can be useful (it helps colour blind people read
graphs for instance), but I think this is the right decision for GrMoEx.
You went for pch = 20, and not pch = 16? I like 20 because I can make plots
where the outline is a solid, bold colour and the fill is paler with an
alpha <1. This means you can always see clearly where the markers are, but
the transparency helps show how many overlap. (To be honest I combine pch =
1 alpha = 1 with pch = 16 alpha = <1). I don't think this is what you
should do here by the way - just making conversation. But would pch = 16
not be better for GrMoEx?



----------------------------------------------------------------
Dr Michael Wallace
Research Associate in Archaeobotany
Departmental Publicity & Marketing Officer

University of Sheffield, Department of Archaeology,
Northgate House, West Street, Sheffield, S1 4ET, UK.
Room 103 - SCALE
<https://www.sheffield.ac.uk/archaeology/research/scale> research
centre
+44 (0)114 22 22933

http://www.sheffield.ac.uk/archaeology/people/wallace
<http://www.shef.ac.uk/archaeology/people/wallace>
----------------------------------------------------------------
Sheffield Archaeology on Facebook
<http://www.facebook.com/ArchaeologySheffield> and YouTube
<http://www.youtube.com/ArchaeologyShef>
----------------------------------------------------------------


*Please note I am employed part-time; normal workdays:Tues & Thurs
mornings, and Weds all day.*

**Comment by vbonhomme** [comment]
the missing data (all empty) is now solved I guess. just tried sth late
yesterday and forgot to remove a line...
pch is now 16. feel free to make changes (line 121)

2016-01-13 12:38 GMT+00:00 Michael Paul Wallace <notifications@github.com>:

> Having different symbols can be useful (it helps colour blind people read
> graphs for instance), but I think this is the right decision for GrMoEx.
> You went for pch = 20, and not pch = 16? I like 20 because I can make plots
> where the outline is a solid, bold colour and the fill is paler with an
> alpha <1. This means you can always see clearly where the markers are, but
> the transparency helps show how many overlap. (To be honest I combine pch =
> 1 alpha = 1 with pch = 16 alpha = <1). I don't think this is what you
> should do here by the way - just making conversation. But would pch = 16
> not be better for GrMoEx?
>
>
>
> ----------------------------------------------------------------
> Dr Michael Wallace
> Research Associate in Archaeobotany
> Departmental Publicity & Marketing Officer
>
> University of Sheffield, Department of Archaeology,
> Northgate House, West Street, Sheffield, S1 4ET, UK.
> Room 103 - SCALE
> <https://www.sheffield.ac.uk/archaeology/research/scale> research
> centre
> +44 (0)114 22 22933
>
> http://www.sheffield.ac.uk/archaeology/people/wallace
> <http://www.shef.ac.uk/archaeology/people/wallace>
> ----------------------------------------------------------------
> Sheffield Archaeology on Facebook
> <http://www.facebook.com/ArchaeologySheffield> and YouTube
> <http://www.youtube.com/ArchaeologyShef>
> ----------------------------------------------------------------
>
>
> *Please note I am employed part-time; normal workdays:Tues & Thurs
> mornings, and Weds all day.*
>
> On 12 January 2016 at 19:09, Vincent Bonhomme <notifications@github.com>
> wrote:
>
> > turned all of them to pch=20. this option bothered me as well. will be
> > removed in a further Momocs version: see vbonhomme/Momocs#116
> > <https://github.com/vbonhomme/Momocs/issues/116>
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/vbonhomme/GrMoEx/issues/57#issuecomment-171018481>.
>
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/vbonhomme/GrMoEx/issues/57#issuecomment-171278930>.
>



-- 
vincentbonhomme.fr <http://www.vincentbonhomme.fr>
