### ISSUE TITLE
Scrollable side panel

### ISSUE THREAD

**Issue by MikePapaWhisky** [vbonhomme/GrMoEx#59]
*I think we've discussed this before; I think you said can't be done, but as I'm not sure and I'd really like it I'm asking again.*

Is it possible to scroll open and down the side panel without the plot area scrolling. This would mean the lower options in the menu can be changed whilst the plot remains visible. Whilst the cosmetic variables shouldn't be changed so often, it is somewhat annoying to try and pick appropriate cosmetic variables whilst scrolling up and down to see the plot.

**Comment by vbonhomme** [comment]
now feasible in a reasonably dirty way but you may need to adjust a bit the number before vh in the line that starts with ```.well { max-height: 120vh;```

**Comment by MikePapaWhisky** [comment]
Like it. Does the job well enough.



----------------------------------------------------------------
Dr Michael Wallace
Research Associate in Archaeobotany
Departmental Publicity & Marketing Officer

University of Sheffield, Department of Archaeology,
Northgate House, West Street, Sheffield, S1 4ET, UK.
Room 103 - SCALE
<https://www.sheffield.ac.uk/archaeology/research/scale> research
centre
+44 (0)114 22 22933

http://www.sheffield.ac.uk/archaeology/people/wallace
<http://www.shef.ac.uk/archaeology/people/wallace>
----------------------------------------------------------------
Sheffield Archaeology on Facebook
<http://www.facebook.com/ArchaeologySheffield> and YouTube
<http://www.youtube.com/ArchaeologyShef>
----------------------------------------------------------------


*Please note I am employed part-time; normal workdays:Tues & Thurs
mornings, and Weds all day.*
