### ISSUE TITLE
Save to PDF

### ISSUE THREAD

**Issue by MikePapaWhisky** [vbonhomme/GrMoEx#60]
I see in the code that there were a few attempts at a save to pdf function. I don't recall why this feature was abandoned, but it would be useful. Right-click on the plot area only permits saving as PNG, which has limited resolution; I discovered this when trying to prove that the ellipse axes have three thicknesses (which are all below the resolution of the screen being used).

**Comment by vbonhomme** [comment]
to me ellipses is a secondary problem (as the N are not crazy, and the confidence will be an option soon, etc.). you should open the GrMoEx in an explorer, then save it. resolution is improved on my machine.
otherwise, if you still want it: find, around lines 530 '''tabPanel("PCA" ''' and uncomment the lines below, see the comments there. I could do it for every plot but that would be a loss of time: in the last R version we are allowed a "save last plot" trick. Turning, in this version (mine, yours probably) all plots into a PDF action button would cost me a lot of time and GrMoEx a lot of ugly and repeated (since hard to function-ize) lines.

**Comment by MikePapaWhisky** [comment]
OK, point taken. I tried the open in browser route, but didn't improve
resolution. It did, however, resolve something Glynis was getting
frustrated by - the file names. In RStudio they are a long string of code
and lack the file extension (which can easily be forgotten to add by hand).
In browser (Chrome) the default filename was download.png. Maybe GrMoEx
should be set to always open in browser - my only reservation is that it
took Chrome a lot long to launch than a new RStudio window.

Would it be any quicker (and more elegant) to have a button that saves all
the plots (i.e. those along the top tabs), ideally with text specifying the
selected parameters. In that case whenever you find an interesting pattern
you just hit the single button which saves all of the plots (and therefore
the one you're interested in), at high resolution with the information
needed to replicate the pattern later. Glynis didn't seem thrilled by this
idea, so if its a pain to do then don't bother - but if its feasible then
maybe we should explore using it.

M



----------------------------------------------------------------
Dr Michael Wallace
Research Associate in Archaeobotany
Departmental Publicity & Marketing Officer

University of Sheffield, Department of Archaeology,
Northgate House, West Street, Sheffield, S1 4ET, UK.
Room 103 - SCALE
<https://www.sheffield.ac.uk/archaeology/research/scale> research
centre
+44 (0)114 22 22933

http://www.sheffield.ac.uk/archaeology/people/wallace
<http://www.shef.ac.uk/archaeology/people/wallace>
----------------------------------------------------------------
Sheffield Archaeology on Facebook
<http://www.facebook.com/ArchaeologySheffield> and YouTube
<http://www.youtube.com/ArchaeologyShef>
----------------------------------------------------------------


*Please note I am employed part-time; normal workdays:Tues & Thurs
mornings, and Weds all day.*

**Comment by vbonhomme** [comment]
it is a pain dude, as it was not planned (R is also to blame) from the
beginning it should result in a big mess for me to do it :-(

2016-01-13 12:34 GMT+00:00 Michael Paul Wallace <notifications@github.com>:

> OK, point taken. I tried the open in browser route, but didn't improve
> resolution. It did, however, resolve something Glynis was getting
> frustrated by - the file names. In RStudio they are a long string of code
> and lack the file extension (which can easily be forgotten to add by hand).
> In browser (Chrome) the default filename was download.png. Maybe GrMoEx
> should be set to always open in browser - my only reservation is that it
> took Chrome a lot long to launch than a new RStudio window.
>
> Would it be any quicker (and more elegant) to have a button that saves all
> the plots (i.e. those along the top tabs), ideally with text specifying the
> selected parameters. In that case whenever you find an interesting pattern
> you just hit the single button which saves all of the plots (and therefore
> the one you're interested in), at high resolution with the information
> needed to replicate the pattern later. Glynis didn't seem thrilled by this
> idea, so if its a pain to do then don't bother - but if its feasible then
> maybe we should explore using it.
>
> M
>
>
>
> ----------------------------------------------------------------
> Dr Michael Wallace
> Research Associate in Archaeobotany
> Departmental Publicity & Marketing Officer
>
> University of Sheffield, Department of Archaeology,
> Northgate House, West Street, Sheffield, S1 4ET, UK.
> Room 103 - SCALE
> <https://www.sheffield.ac.uk/archaeology/research/scale> research
> centre
> +44 (0)114 22 22933
>
> http://www.sheffield.ac.uk/archaeology/people/wallace
> <http://www.shef.ac.uk/archaeology/people/wallace>
> ----------------------------------------------------------------
> Sheffield Archaeology on Facebook
> <http://www.facebook.com/ArchaeologySheffield> and YouTube
> <http://www.youtube.com/ArchaeologyShef>
> ----------------------------------------------------------------
>
>
> *Please note I am employed part-time; normal workdays:Tues & Thurs
> mornings, and Weds all day.*
>
> On 12 January 2016 at 19:05, Vincent Bonhomme <notifications@github.com>
> wrote:
>
> > to me ellipses is a secondary problem (as the N are not crazy, and the
> > confidence will be an option soon, etc.). you should open the GrMoEx in
> an
> > explorer, then save it. resolution is improved on my machine.
> > otherwise, if you still want it: find, around lines 530 '''tabPanel("PCA"
> > ''' and uncomment the lines below, see the comments there. I could do it
> > for every plot but that would be a loss of time: in the last R version we
> > are allowed a "save last plot" trick. Turning, in this version (mine,
> yours
> > probably) all plots into a PDF action button would cost me a lot of time
> > and GrMoEx a lot of ugly and repeated (since hard to function-ize) lines.
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/vbonhomme/GrMoEx/issues/60#issuecomment-171017494>.
>
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/vbonhomme/GrMoEx/issues/60#issuecomment-171277784>.
>



-- 
vincentbonhomme.fr <http://www.vincentbonhomme.fr>

**Comment by MikePapaWhisky** [comment]
no worries. just checking.



----------------------------------------------------------------
Dr Michael Wallace
Research Associate in Archaeobotany
Departmental Publicity & Marketing Officer

University of Sheffield, Department of Archaeology,
Northgate House, West Street, Sheffield, S1 4ET, UK.
Room 103 - SCALE
<https://www.sheffield.ac.uk/archaeology/research/scale> research
centre
+44 (0)114 22 22933

http://www.sheffield.ac.uk/archaeology/people/wallace
<http://www.shef.ac.uk/archaeology/people/wallace>
----------------------------------------------------------------
Sheffield Archaeology on Facebook
<http://www.facebook.com/ArchaeologySheffield> and YouTube
<http://www.youtube.com/ArchaeologyShef>
----------------------------------------------------------------


*Please note I am employed part-time; normal workdays:Tues & Thurs
mornings, and Weds all day.*
