### ISSUE TITLE
Clustering analysis error

### ISSUE THREAD

**Issue by MikePapaWhisky** [vbonhomme/GrMoEx#63]
When selecting the clustering tab I get this error - I know the packages for clustering are a pain to install, but as far as I am aware they are in place.

`Warning: Error in : Aesthetics must be either length 1 or the same as the data (2745): x, y, xend, yend, colour`
`Stack trace (innermost first):`
   ` 72: output$clust`
  `   5: runApp`
  `   4: eval [C:/Users/Wallace/Dropbox/Origins shared (VB)/EOA_arch/code/3_grmoex.r#797]`
  `   3: eval`
    ` 2: withVisible`
`     1: source`

**Comment by MikePapaWhisky** [comment]
Just discovered that this only applies to particular layout of cluster analsysi

**Comment by vbonhomme** [comment]
so, is this a problem or not ?

2016-01-14 12:45 GMT+00:00 Michael Paul Wallace <notifications@github.com>:

> Just discovered that this only applies to particular layout of cluster
> analsysi
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/vbonhomme/GrMoEx/issues/63#issuecomment-171635075>.
>



-- 
vincentbonhomme.fr <http://www.vincentbonhomme.fr>

**Comment by MikePapaWhisky** [comment]
Still a problem at my end. Is it OK for you - in which case it's likely a
package installation problem.

**Comment by vbonhomme** [comment]
some detaisl would be useful

2016-01-17 12:56 GMT+01:00 Michael Paul Wallace <notifications@github.com>:

> Still a problem at my end. Is it OK for you - in which case it's likely a
> package installation problem.
> On 14 Jan 2016 18:52, "Vincent Bonhomme" <notifications@github.com> wrote:
>
> > so, is this a problem or not ?
> >
> > 2016-01-14 12:45 GMT+00:00 Michael Paul Wallace <
> notifications@github.com
> > >:
> >
> > > Just discovered that this only applies to particular layout of cluster
> > > analsysi
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <https://github.com/vbonhomme/GrMoEx/issues/63#issuecomment-171635075
> >.
> > >
> >
> >
> >
> > --
> > vincentbonhomme.fr <http://www.vincentbonhomme.fr>
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/vbonhomme/GrMoEx/issues/63#issuecomment-171737100>.
>
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/vbonhomme/GrMoEx/issues/63#issuecomment-172317620>.
>



-- 
vincentbonhomme.fr <http://www.vincentbonhomme.fr>

**Comment by MikePapaWhisky** [comment]
Next time I'm running GrMoEx...

**Comment by vbonhomme** [comment]
fixed but requires Momocs >= 0.9.71
