### ISSUE TITLE
Traditional measurements as factor options

### ISSUE THREAD

**Issue by MikePapaWhisky** [vbonhomme/GrMoEx#64]
Is it possible to use the traditional measurements (length, breadth, thickness and calculated ellipsoid volume; i.e. those from the ````Traditional```` tab) as factors for the PCA plot, _et al_?

We are interested in exploring whether certain grains are given certain identifications based on their size.

**Comment by vbonhomme** [comment]
well, we still dont handle continuous variables. but we should. so I'll
work on it. when, I dont know. a big mess to implement.

2016-01-14 11:52 GMT+00:00 Michael Paul Wallace <notifications@github.com>:

> Is it possible to use the traditional measurements (length, breadth,
> thickness and calculated ellipsoid volume; i.e. those from the Traditional
> tab) as factors for the PCA plot, *et al*?
>
> We are interested in exploring whether certain grains are given certain
> identifications based on their size.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/vbonhomme/GrMoEx/issues/64>.
>



-- 
vincentbonhomme.fr <http://www.vincentbonhomme.fr>

**Comment by vbonhomme** [comment]
https://github.com/vbonhomme/Momocs/issues/86

2016-01-14 18:19 GMT+00:00 Vincent Bonhomme <bonhomme.vincent@gmail.com>:

> well, we still dont handle continuous variables. but we should. so I'll
> work on it. when, I dont know. a big mess to implement.
>
> 2016-01-14 11:52 GMT+00:00 Michael Paul Wallace <notifications@github.com>
> :
>
>> Is it possible to use the traditional measurements (length, breadth,
>> thickness and calculated ellipsoid volume; i.e. those from the
>> Traditional tab) as factors for the PCA plot, *et al*?
>>
>> We are interested in exploring whether certain grains are given certain
>> identifications based on their size.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/vbonhomme/GrMoEx/issues/64>.
>>
>
>
>
> --
> vincentbonhomme.fr <http://www.vincentbonhomme.fr>
>



-- 
vincentbonhomme.fr <http://www.vincentbonhomme.fr>

**Comment by MikePapaWhisky** [comment]
Continuous factors would be appreciated for date (e.g. MeanBC) too. If that
helps motivate you.

We wouldn't want to do an LDA or Cluster Analysis, using a continues
variable. It is only needed as a graphical coding factor in PCA plots,
which ggplot2 can handle with ease.

**Comment by vbonhomme** [comment]
if you discover how to do an LDA using a continuous, give me a call.
mischeivous V.

2016-01-17 13:01 GMT+01:00 Michael Paul Wallace <notifications@github.com>:

> Continuous factors would be appreciated for date (e.g. MeanBC) too. If that
> helps motivate you.
>
> We wouldn't want to do an LDA or Cluster Analysis, using a continues
> variable. It is only needed as a graphical coding factor in PCA plots,
> which ggplot2 can handle with ease.
> On 14 Jan 2016 18:19, "Vincent Bonhomme" <notifications@github.com> wrote:
>
> > well, we still dont handle continuous variables. but we should. so I'll
> > work on it. when, I dont know. a big mess to implement.
> >
> > 2016-01-14 11:52 GMT+00:00 Michael Paul Wallace <
> notifications@github.com
> > >:
> >
> > > Is it possible to use the traditional measurements (length, breadth,
> > > thickness and calculated ellipsoid volume; i.e. those from the
> > Traditional
> > > tab) as factors for the PCA plot, *et al*?
> > >
> > > We are interested in exploring whether certain grains are given certain
> > > identifications based on their size.
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <https://github.com/vbonhomme/GrMoEx/issues/64>.
> > >
> >
> >
> >
> > --
> > vincentbonhomme.fr <http://www.vincentbonhomme.fr>
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/vbonhomme/GrMoEx/issues/64#issuecomment-171728446>.
>
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/vbonhomme/GrMoEx/issues/64#issuecomment-172317789>.
>



-- 
vincentbonhomme.fr <http://www.vincentbonhomme.fr>

**Comment by MikePapaWhisky** [comment]
As per previous email. We're not interested in using as fac for LDA, just
as fac for PCA plot. LDA tab can just have the error "Don't even think
about using this continues variable as a grouping variable in LDA. And
don't you dare click the clustering tab".

**Comment by vbonhomme** [comment]
I'm not gonna implement all the possible cases, at some point I trust you
using it

2016-01-19 20:47 GMT+01:00 Michael Paul Wallace <notifications@github.com>:

> As per previous email. We're not interested in using as fac for LDA, just
> as fac for PCA plot. LDA tab can just have the error "Don't even think
> about using this continues variable as a grouping variable in LDA. And
> don't you dare click the clustering tab".
> On 17 Jan 2016 14:30, "Vincent Bonhomme" <notifications@github.com> wrote:
>
> > if you discover how to do an LDA using a continuous, give me a call.
> > mischeivous V.
> >
> > 2016-01-17 13:01 GMT+01:00 Michael Paul Wallace <
> notifications@github.com
> > >:
> >
> > > Continuous factors would be appreciated for date (e.g. MeanBC) too. If
> > that
> > > helps motivate you.
> > >
> > > We wouldn't want to do an LDA or Cluster Analysis, using a continues
> > > variable. It is only needed as a graphical coding factor in PCA plots,
> > > which ggplot2 can handle with ease.
> > > On 14 Jan 2016 18:19, "Vincent Bonhomme" <notifications@github.com>
> > wrote:
> > >
> > > > well, we still dont handle continuous variables. but we should. so
> I'll
> > > > work on it. when, I dont know. a big mess to implement.
> > > >
> > > > 2016-01-14 11:52 GMT+00:00 Michael Paul Wallace <
> > > notifications@github.com
> > > > >:
> > > >
> > > > > Is it possible to use the traditional measurements (length,
> breadth,
> > > > > thickness and calculated ellipsoid volume; i.e. those from the
> > > > Traditional
> > > > > tab) as factors for the PCA plot, *et al*?
> > > > >
> > > > > We are interested in exploring whether certain grains are given
> > certain
> > > > > identifications based on their size.
> > > > >
> > > > > —
> > > > > Reply to this email directly or view it on GitHub
> > > > > <https://github.com/vbonhomme/GrMoEx/issues/64>.
> > > > >
> > > >
> > > >
> > > >
> > > > --
> > > > vincentbonhomme.fr <http://www.vincentbonhomme.fr>
> > > >
> > > > —
> > > > Reply to this email directly or view it on GitHub
> > > > <
> https://github.com/vbonhomme/GrMoEx/issues/64#issuecomment-171728446
> > >.
> > >
> > > >
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <https://github.com/vbonhomme/GrMoEx/issues/64#issuecomment-172317789
> >.
> > >
> >
> >
> >
> > --
> > vincentbonhomme.fr <http://www.vincentbonhomme.fr>
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/vbonhomme/GrMoEx/issues/64#issuecomment-172329596>.
>
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/vbonhomme/GrMoEx/issues/64#issuecomment-172964886>.
>



-- 
vincentbonhomme.fr <http://www.vincentbonhomme.fr>

**Comment by vbonhomme** [comment]
fixed. requires Momocs >= 0.9.71 and the last GrMoEx version. Also checking the checkbox (no better option I think, since factor nature must be retained elsewhere).
