### ISSUE TITLE
Fix Map

### ISSUE THREAD

**Issue by MikePapaWhisky** [vbonhomme/GrMoEx#7]
Error: object 'crescent_map' not found. On selecting the tav=b in Shiny.
From console:

    Error in ggmap(crescent_map, darken = c(3/4, color = "#FFFFFF")) : 
    object 'crescent_map' not found

**Comment by MikePapaWhisky** [comment]
Line 107 to
    gg <- ggmap(map, darken=c(3/4, color="#FFFFFF")) 
Seems to fix but not sure if that's the right move.

**Comment by vbonhomme** [comment]
fixed

2015-07-09 12:37 GMT+02:00 Michael Paul Wallace <notifications@github.com>:

> Error: object 'crescent_map' not found. On selecting the tav=b in Shiny.
> From console:
>
> Error in ggmap(crescent_map, darken = c(3/4, color = "#FFFFFF")) :
> object 'crescent_map' not found
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/vbonhomme/GrMoEx/issues/7>.
>



-- 
vincentbonhomme.fr <http://www.vincentbonhomme.fr>

**Comment by vbonhomme** [comment]
every single time you touch sth in the map section a kitten dies.
