### ISSUE TITLE
SHK does not appear on Map

### ISSUE THREAD

**Issue by MikePapaWhisky** [vbonhomme/GrMoEx#8]
SHK (sitephase prefix SHEA) does not appear on the map.

**Comment by vbonhomme** [comment]
what do you mean ?
you want the map with site phases instead ?
all circles would be staked then and not sure jitter could help.

2015-07-09 12:42 GMT+02:00 Michael Paul Wallace <notifications@github.com>:

> SHK (sitephase prefix SHEA) does not appear on the map.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/vbonhomme/GrMoEx/issues/8>.
>



-- 
vincentbonhomme.fr <http://www.vincentbonhomme.fr>

**Comment by MikePapaWhisky** [comment]
Nope. If you look at the sample size table (with all taxa and sites active) you will see some samples come from the site SHK. This site is located in western Iran. It doesn't, however, appear on the map.

**Comment by vbonhomme** [comment]
didt understand it was a matter of long range.
fixed (the generic way) now.

**Comment by MikePapaWhisky** [comment]
I knew you'd have gone non-generic to start with. You're so dirty.
