### ISSUE TITLE
Tboe(cf) 

### ISSUE THREAD

**Issue by MikePapaWhisky** [vbonhomme/GrMoEx#9]
The two Tboe(cf) samples should be re-branded TBOE-MON permanently (not just at a grouping level). I assume the taxa names come direct from the silhouette image files, do they need to be changed there?

**Comment by vbonhomme** [comment]
feel free to do it, line 54+ III_Prepare.R

2015-07-09 13:01 GMT+02:00 Michael Paul Wallace <notifications@github.com>:

> The two Tboe(cf) samples should be re-branded TBOE-MON permanently (not
> just at a grouping level). I assume the taxa names come direct from the
> silhouette image files, do they need to be changed there?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/vbonhomme/GrMoEx/issues/9>.
>



-- 
vincentbonhomme.fr <http://www.vincentbonhomme.fr>

**Comment by MikePapaWhisky** [comment]
Done it. Fine for now, but a rule is not the best option in this case. TBOE(cf) is a perfectly legitimate taxon (unlike "Tboe "). In the future we may add taxa of Tboe(cf) that we want to keep as such. All we're saying for the moment is that the two samples (that just so happen to be the only Tboe(cf) in the current dataset) should be moved to Tboe-mono.

**Comment by vbonhomme** [comment]
we could make a local rule but not fan of this option.
anyway file names are already quite unperfect already (see I_Import.R)
(errare humanum est), but we would better move it the local rule there then.

2015-07-09 13:21 GMT+02:00 Michael Paul Wallace <notifications@github.com>:

> Closed #9 <https://github.com/vbonhomme/GrMoEx/issues/9>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/vbonhomme/GrMoEx/issues/9#event-351752764>.
>



-- 
vincentbonhomme.fr <http://www.vincentbonhomme.fr>
